#!/usr/bin/env python3
"""catbench_jobgen.py — templates + emitters for one catbench model job.

Owns the three things every catbench run needs on disk (Principle 2: "the
file is the action" — nothing executes that does not first exist as a file
the user can rerun byte-identically without Claude):

  1. `render_model_script`  — the per-model catbench python script, a verbatim
     `resolve()` codegen (absolute weight paths and all — see F13 in the
     consensus plan: 11/20 families ship absolute host weight paths, so a
     host-independence assertion on this file is impossible by construction
     and is deliberately NOT part of this module's test suite).
  2. `render_runner_sh`     — the AC7 unit. `env_run` (NequIP/DeePMD/DPA4) is
     an allow-listed dict applied to a SUBPROCESS environment by resolve();
     it never lived in the `.py` text, so the `.py` alone was never
     rerunnable for those three frameworks. This `.sh` exports it, `cd`s to
     the absolute benchmark workdir first (N4 — catbench writes into
     `cwd/result/`; without the `cd`, rerunning this file from elsewhere
     silently starts a fresh `result/`), then execs the `.py`.
  3. `render_slurm_sh`      — an SBATCH header followed by the IDENTICAL body
     as `render_runner_sh` (`_render_body`), so local and SLURM execution
     cannot drift into two emitters that disagree.

`emit()` writes all of the above under `<workdir>/jobs/`.

No GPU, no torch, no catbench import here — this whole module is GPU-free and
exercised directly by tests/test_catbench_jobgen.py.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

# The exact per-model catbench script. Runs INSIDE the model's own env
# interpreter (resolve()'s "python"), builds calc_num calculator instances
# from the registry's import+inference lines, and runs catbench's
# AdsorptionCalculation with config={mlip_name, benchmark} — the skeleton
# `run_examples/catbench_quickstart.py` has always used. Moved here verbatim
# so a SINGLE module owns catbench codegen (was `_build_script` in
# catbench_quickstart.py).
_CATBENCH_TEMPLATE = '''\
import warnings
warnings.filterwarnings("ignore")
{version_guard}from catbench.adsorption import AdsorptionCalculation
{d3_import}{import_lines}

calc_num = {calc_num}
calculators = []
print("Calculators Initializing...")
for i in range(calc_num):
    print(f"{{i}}th calculator")
{inference_lines}
{d3_apply}    calculators.append(calc)

config = {{"mlip_name": {mlip_name!r}, "benchmark": {benchmark!r}}}
AdsorptionCalculation(calculators, **config).run()
print("[catbench] {mlip_name} done")
'''

# Marks the generated runner unit's contract in one line, so a diff of the
# emitted file always states what it is even outside this module's docstring.
_GEN_COMMENT = "# generated by scripts/catbench_jobgen.py -- rerun this file to reproduce the run"


# The approved-version guard (recipes/catbench.md §2 "Version rule"): the job
# refuses to run under any other catbench than the one the plan approved, so
# a rerun cannot silently drift to whatever an env happens to hold.
_VERSION_GUARD = '''\
import catbench as _cb, sys as _sys
if _cb.__version__ != {version!r}:
    _sys.stderr.write("[stop] approved catbench {version} but this env has " + _cb.__version__ + "\\n")
    _sys.exit(3)
'''


def render_model_script(spec: dict, mlip_name: str, benchmark: str, calc_num: int, d3: bool,
                        catbench_version: str | None = None) -> str:
    """Render the per-model catbench script from a `resolve()` spec.

    Verbatim `resolve()` output: imports/inference lines are copied as-is,
    including any absolute host weight path they carry (F13). Byte-identical
    for the same inputs (AC7's determinism property, C3). `catbench_version`
    (optional) inserts the approved-version guard above the catbench import.
    """
    indent = "    "
    import_lines = "\n".join(spec["imports"])
    inference_lines = "\n".join(indent + ln for ln in spec["inference"])
    d3_import = "from catbench.dispersion import DispersionCorrection\n" if d3 else ""
    d3_apply = f"{indent}calc = DispersionCorrection().apply(calc)\n" if d3 else ""
    return _CATBENCH_TEMPLATE.format(
        version_guard=_VERSION_GUARD.format(version=catbench_version) if catbench_version else "",
        d3_import=d3_import,
        import_lines=import_lines,
        calc_num=calc_num,
        inference_lines=inference_lines,
        d3_apply=d3_apply,
        mlip_name=mlip_name,
        benchmark=benchmark,
    )


def _render_body(spec: dict, jobfile: Path, workdir: Path) -> str:
    """The shared body of `render_runner_sh` and `render_slurm_sh`.

    Deliberately the ONLY place either renderer writes `cd`/`export`/`exec` —
    `render_slurm_sh`'s output always ENDS with exactly this text (see the
    byte-identical-below-the-header assertion in tests/test_catbench_jobgen.py),
    so local and SLURM cannot silently diverge.
    """
    lines = [
        _GEN_COMMENT,
        "set -eu",
        f'cd "{Path(workdir).resolve()}"',  # N4: catbench writes into cwd/result/
    ]
    # The env's own bin goes first on PATH, as oh_my_mlip/provider.py does when it
    # dispatches inference: openequivariance (NequIP/Allegro) JIT-compiles its CUDA
    # extension at first use and shells out to `ninja`, which is installed only in the
    # env. env_run is exported after this, so its overrides still win.
    lines.append(f'export PATH="{Path(spec["python"]).resolve().parent}${{PATH:+:$PATH}}"')
    for key, value in spec.get("env_run", {}).items():
        lines.append(f'export {key}="{value}"')
    lines.append(f'exec "{spec["python"]}" "{Path(jobfile).resolve()}"')
    return "\n".join(lines) + "\n"


def render_runner_sh(spec: dict, jobfile: Path, workdir: Path) -> str:
    """The AC7 unit: `set -eu`, `cd` to the absolute workdir, one `export`
    per `env_run` key, then `exec` the materialized `.py` (never `python -c`).
    """
    return "#!/bin/sh\n" + _render_body(spec, jobfile, workdir)


def render_slurm_sh(
    spec: dict,
    jobfile: Path,
    workdir: Path,
    *,
    job_name: str,
    partition: str = "gpu",
) -> str:
    """An SBATCH header followed by the IDENTICAL body as `render_runner_sh`.

    One body, two wrappers (C2/C17): local and SLURM execution stay a single
    source of truth. No `sbatch` is issued here or anywhere in this module —
    emission only.
    """
    workdir_abs = Path(workdir).resolve()
    header = "\n".join(
        [
            f"#SBATCH --job-name={job_name}",
            f"#SBATCH --partition={partition}",
            f"#SBATCH --output={workdir_abs}/jobs/{job_name}.slurm.out",
            f"#SBATCH --error={workdir_abs}/jobs/{job_name}.slurm.err",
            "#SBATCH --ntasks=1",
            "#SBATCH --gres=gpu:1",
        ]
    ) + "\n"
    return "#!/bin/sh\n" + header + _render_body(spec, jobfile, workdir)


def emit(
    spec: dict,
    mlip_name: str,
    benchmark: str,
    calc_num: int,
    d3: bool,
    workdir: Path,
    *,
    slurm: bool = False,
    partition: str = "gpu",
    catbench_version: str | None = None,
    overwrite: bool = False,
) -> dict:
    """Materialize `jobs/catbench_<mlip_name>.py` + `jobs/run_catbench_<mlip_name>.sh`
    (and, if `slurm`, `jobs/run_slurm_<mlip_name>.sh`) under `workdir`.

    Returns ``{"py": Path, "sh": Path[, "slurm": Path, "meta": Path],
    "reused": [...]}``. Writing twice with the same inputs produces
    byte-identical files (AC7's determinism property) — this function does not
    read the clock, the host, or any per-run state. `catbench_version` pins the
    job to the approved release (guard inside the `.py`, recorded in
    `jobs/catbench_<mlip_name>.meta.json`). A rerun keeps files whose bytes
    are unchanged and refuses (`FileExistsError`) to replace files that would
    change unless `overwrite=True` — see `_write_planned`.
    """
    workdir = Path(workdir).resolve()
    jobs_dir = workdir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    py_path = jobs_dir / f"catbench_{mlip_name}.py"
    sh_path = jobs_dir / f"run_catbench_{mlip_name}.sh"
    planned = {
        "py": (py_path, render_model_script(spec, mlip_name, benchmark, calc_num, d3, catbench_version), False),
        "sh": (sh_path, render_runner_sh(spec, py_path, workdir), True),
    }
    if slurm:
        planned["slurm"] = (
            jobs_dir / f"run_slurm_{mlip_name}.sh",
            render_slurm_sh(spec, py_path, workdir, job_name=f"catbench_{mlip_name}", partition=partition),
            True,
        )
    if catbench_version is not None:
        planned["meta"] = (
            jobs_dir / f"catbench_{mlip_name}.meta.json",
            json.dumps({
                "mlip_name": mlip_name, "benchmark": benchmark, "calc_num": calc_num, "d3": d3,
                "catbench_version": catbench_version, "python": spec["python"],
                "source": spec.get("source", "registry"), "calc_file": spec.get("calc_file"),
                "calc_file_sha256": spec.get("calc_file_sha256"),
            }, indent=2, sort_keys=True) + "\n",
            False,
        )
    return _write_planned(planned, overwrite=overwrite)


def _write_planned(planned: dict, *, overwrite: bool) -> dict:
    """Write `{kind: (path, content, executable)}` under the rerun rule: an
    existing file with identical bytes is kept (the rerun executes the file
    that was generated before); an existing file with DIFFERENT bytes is never
    replaced silently — `FileExistsError` names every such file and nothing is
    written, unless `overwrite` was passed explicitly (`--regenerate`).
    Returns `{kind: Path, ..., "reused": [kinds kept unchanged]}`."""
    stale = []
    reused = []
    for kind, (path, content, _x) in planned.items():
        if path.exists():
            if path.read_text() == content:
                reused.append(kind)
            elif not overwrite:
                stale.append(path)
    if stale:
        raise FileExistsError(
            "existing job file(s) differ from what these inputs would generate: "
            + ", ".join(str(p) for p in stale)
            + " — rerun the existing files as they are, or pass --regenerate to replace them"
        )
    result = {}
    for kind, (path, content, executable) in planned.items():
        if kind not in reused:
            path.write_text(content)
            if executable:
                path.chmod(0o755)
        result[kind] = path
    result["reused"] = reused
    return result


# ── non-registry calculator path (recipes/catbench.md §4) ────────────────────
# The user's own ASE calculator file + the interpreter that runs it. The file
# must define `make_calculator()` returning an ASE calculator; it is loaded by
# absolute path inside the job, so the user's code is the calculator source —
# nothing is installed, and models.json is never edited.
_CALC_FILE_IMPORTS = [
    "import importlib.util as _ilu",
    "_spec = _ilu.spec_from_file_location('omm_user_calc', {path!r})",
    "omm_user_calc = _ilu.module_from_spec(_spec)",
    "_spec.loader.exec_module(omm_user_calc)",
]

_WITNESS_TEMPLATE = '''\
{gen_comment}
import json, sys
import numpy as np
{import_lines}
{structure_lines}
calc = omm_user_calc.make_calculator()
atoms.calc = calc
energy = float(atoms.get_potential_energy())
forces = np.asarray(atoms.get_forces())
record = {{"name": {name!r}, "python": sys.executable, "n_atoms": len(atoms), "energy_eV": energy,
          "calc_file": {calc_file!r}, "calc_file_sha256": {calc_sha!r},
          "forces_shape": list(forces.shape), "forces_finite": bool(np.isfinite(forces).all()),
          "ok": bool(np.isfinite(energy)) and forces.shape == (len(atoms), 3) and bool(np.isfinite(forces).all())}}
open({out!r}, "w").write(json.dumps(record, indent=2) + "\\n")
print(json.dumps(record))
sys.exit(0 if record["ok"] else 3)
'''


def spec_from_calc_file(calc_file: Path, python: str, name: str) -> dict:
    """Build a resolve()-shaped spec from the user's calculator file.

    Refuses (ValueError) when the file does not parse or does not define
    `make_calculator`, so the failure is at plan time, not inside a GPU job.
    """
    import ast
    import hashlib

    calc_file = Path(calc_file).resolve()
    python = str(Path(python).resolve()) if Path(python).exists() else python
    if not calc_file.is_file():
        raise ValueError(f"calculator file not found: {calc_file}")
    if not Path(python).is_file():
        raise ValueError(f"interpreter not found: {python}")
    tree = ast.parse(calc_file.read_text(), filename=str(calc_file))
    if not any(isinstance(n, ast.FunctionDef) and n.name == "make_calculator" for n in tree.body):
        raise ValueError(f"{calc_file} must define a module-level `def make_calculator():` returning an ASE calculator")
    return {
        "python": python,
        "imports": [ln.format(path=str(calc_file)) for ln in _CALC_FILE_IMPORTS],
        "inference": ["calc = omm_user_calc.make_calculator()"],
        "env_run": {},
        "version": name,
        "source": "calc-file",
        "calc_file": str(calc_file),
        "calc_file_sha256": hashlib.sha256(calc_file.read_bytes()).hexdigest(),
    }


def render_witness_py(spec: dict, name: str, out_json: Path, structure_file: Path | None = None) -> str:
    """The E/F witness for a non-registry calculator: build it once on a small
    structure (a 2-atom fcc Cu cell by default, or `structure_file` read by
    ASE), print energy + forces shape, write `out_json`, exit 3 on failure."""
    if structure_file is not None:
        structure_lines = f"from ase.io import read\natoms = read({str(Path(structure_file).resolve())!r})"
    else:
        structure_lines = "from ase.build import bulk\natoms = bulk('Cu', 'fcc', a=3.6, cubic=False).repeat((1, 1, 2))"
    return _WITNESS_TEMPLATE.format(
        gen_comment=_GEN_COMMENT, import_lines="\n".join(spec["imports"]),
        structure_lines=structure_lines, name=name, out=str(Path(out_json).resolve()),
        calc_file=spec.get("calc_file"), calc_sha=spec.get("calc_file_sha256"),
    )


def emit_witness(spec: dict, name: str, workdir: Path, structure_file: Path | None = None,
                 *, overwrite: bool = False) -> dict:
    """`jobs/witness_<name>.py` + `jobs/run_witness_<name>.sh` (same body
    renderer as the job runner: cd + env_run exports + exec). Same rerun rule
    as `emit`: a witness whose calculator file changed renders differently and
    is only replaced with `overwrite=True` (`--regenerate`)."""
    workdir = Path(workdir).resolve()
    jobs_dir = workdir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)
    py_path = jobs_dir / f"witness_{name}.py"
    out_json = jobs_dir / f"witness_{name}.json"
    sh_path = jobs_dir / f"run_witness_{name}.sh"
    result = _write_planned({
        "py": (py_path, render_witness_py(spec, name, out_json, structure_file), False),
        "sh": (sh_path, render_runner_sh(spec, py_path, workdir), True),
    }, overwrite=overwrite)
    result["json"] = out_json
    return result


def main(argv: list[str] | None = None) -> int:
    """CLI: one job (+ witness for a non-registry calculator). Emission only —
    `--submit` dispatches through the injectable hook; nothing else executes."""
    import argparse
    import sys

    ap = argparse.ArgumentParser(description="materialize one catbench job (registry model or user calculator file)")
    ap.add_argument("--tag", required=True, help="benchmark tag (raw_data/<tag>_adsorption.json under --workdir)")
    ap.add_argument("--workdir", default=".", help="benchmark workdir (catbench writes cwd/result/)")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--model", help="registry framework name (resolve())")
    src.add_argument("--calc-file", help="user ASE calculator file defining make_calculator()")
    ap.add_argument("--version", default=None, help="registry version (with --model)")
    ap.add_argument("--python", default=None, help="interpreter for --calc-file (required with it)")
    ap.add_argument("--name", default=None, help="mlip_name for --calc-file (default: file stem)")
    ap.add_argument("--structure", default=None, help="ASE-readable structure for the witness (default: 2-atom Cu)")
    ap.add_argument("--calc-num", type=int, default=3)
    ap.add_argument("--d3", action="store_true")
    ap.add_argument("--catbench-version", default=None, help="approved catbench version (guard + meta record)")
    ap.add_argument("--slurm", action="store_true")
    ap.add_argument("--partition", default="gpu")
    ap.add_argument("--submit", action="store_true", help="dispatch the runner through submit() after emission")
    ap.add_argument("--regenerate", action="store_true",
                    help="replace existing job/witness files whose content would change (never silent)")
    args = ap.parse_args(argv)

    workdir = Path(args.workdir).resolve()
    for bad in (_safe_component(args.tag, "--tag"), _safe_component(args.name, "--name") if args.name else None):
        if bad:
            print(f"[stop] {bad}", file=sys.stderr)
            return 2
    if args.calc_num < 1:
        print(f"[stop] --calc-num must be >= 1 (got {args.calc_num})", file=sys.stderr)
        return 2
    data_file = workdir / "raw_data" / f"{args.tag}_adsorption.json"
    if not data_file.is_file():
        print(f"[stop] {data_file} not found — stage or fetch the dataset first", file=sys.stderr)
        return 2
    witness = None
    if args.calc_file:
        if not args.python:
            print("[stop] --calc-file needs --python <interpreter>", file=sys.stderr)
            return 2
        name = args.name or Path(args.calc_file).stem
        if (bad := _safe_component(name, "--name")):
            print(f"[stop] {bad}", file=sys.stderr)
            return 2
        try:
            spec = spec_from_calc_file(Path(args.calc_file), args.python, name)
        except (ValueError, SyntaxError) as exc:
            print(f"[stop] {exc}", file=sys.stderr)
            return 2
        try:
            witness = emit_witness(spec, name, workdir, Path(args.structure) if args.structure else None,
                                   overwrite=args.regenerate)
        except FileExistsError as exc:
            print(f"[stop] {exc}", file=sys.stderr)
            return 3
    else:
        sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
        from oh_my_mlip import RegistryError, resolve  # noqa: E402
        try:
            spec = resolve(args.model, args.version)
        except RegistryError as exc:
            print(f"[stop] {exc}", file=sys.stderr)
            return 2
        name = spec.get("version", args.model)
    mlip_name = name + ("_D3" if args.d3 else "")
    try:
        artifacts = emit(spec, mlip_name, args.tag, args.calc_num, args.d3, workdir,
                         slurm=args.slurm, partition=args.partition, catbench_version=args.catbench_version,
                         overwrite=args.regenerate)
    except FileExistsError as exc:
        print(f"[stop] {exc}", file=sys.stderr)
        return 3
    if witness:
        state = "unchanged, kept" if "py" in witness["reused"] else "written"
        print(f"witness : {witness['sh']}  ({state}; run first; writes {witness['json']})")
    for kind, path in artifacts.items():
        if kind == "reused":
            continue
        state = "unchanged, kept" if kind in artifacts["reused"] else "written"
        print(f"{kind:<8}: {path}  ({state})")
    if args.submit:
        if witness:
            ok, why = witness_passed(witness["json"], spec)
            if not ok:
                print(f"[stop] {why} — run `sh {witness['sh']}` first; the job is not dispatched", file=sys.stderr)
                return 3
        return submit(artifacts.get("slurm", artifacts["sh"]))
    return 0


def witness_passed(witness_json: Path, spec: dict) -> tuple[bool, str]:
    """A non-registry job may be dispatched only after its witness wrote
    `ok: true` for the SAME calculator file (sha256 bound at witness time)."""
    witness_json = Path(witness_json)
    if not witness_json.is_file():
        return False, f"witness record {witness_json} not found"
    try:
        rec = json.loads(witness_json.read_text())
    except ValueError as exc:
        return False, f"witness record unreadable: {exc}"
    if rec.get("ok") is not True:
        return False, f"witness reported ok={rec.get('ok')!r} (energy/forces check failed)"
    if rec.get("calc_file_sha256") != spec.get("calc_file_sha256"):
        return False, "calculator file changed since the witness ran (sha256 differs); re-run the witness"
    return True, "witness ok"


def _safe_component(value: str, what: str) -> str | None:
    """`--tag`/`--name` become file-name components under jobs/ and raw_data/;
    refuse anything that could leave those directories."""
    if not value or value in (".", "..") or "/" in value or "\\" in value or value.startswith("-"):
        return f"{what} {value!r} is not a plain file-name component"
    return None


def _default_submit_hook(target: Path) -> int:
    """`sbatch <target>` for a SLURM script, `sh <target>` for a local runner."""
    target = Path(target)
    cmd = ["sbatch", str(target)] if target.name.startswith("run_slurm_") else ["sh", str(target)]
    return subprocess.run(cmd).returncode


def submit(target: Path, *, hook=None) -> int:
    """Dispatch one emitted `.sh` (never called under `--emit-only`).

    `hook` is injectable so callers (and tests) can verify dispatch without
    invoking a real scheduler or subprocess — the single hook C17/AC7's
    `--submit` flag is described as sitting behind.
    """
    fn = hook or _default_submit_hook
    return fn(Path(target))


if __name__ == "__main__":
    raise SystemExit(main())
