#!/usr/bin/env python3
"""catbench_vasp_stage.py — copy-only staging of a user's VASP tree for catbench.

Upstream `catbench.adsorption.vasp_preprocessing(dataset, coeff_setting)`
(catbench/adsorption/data/vasp.py:260) first runs
`cleanup_vasp_files(keep_files=["OSZICAR", "CONTCAR"])` on the tree it is
given — it DELETES every other file. So it must only ever see a copy, never
the originals and never a symlink tree into them. This script owns that
boundary and nothing else; the conversion itself stays upstream.

Ordered use (recipes/catbench.md §2 C):

  1. scan     — walk the originals WITHOUT following symlinks; list every
                CONTCAR+OSZICAR pair, every half-pair (missing DFT result,
                reported never invented), every symlink (refused), and write
                `mapping_proposal.json`. `slab`/`adslab` coefficients follow
                the upstream convention (adslab − slab − Σ gas); gas terms are
                listed as candidates that the USER confirms — never guessed.
                Its outputs are recorded in the owner marker (`--out` becomes an
                owned destination) and are kept, never rewritten, on a re-scan.
  2. stage    — with the confirmed coefficients (pass `--coeff` from OUTSIDE the
                destination: `<dest>/coeff_setting.json` is an output this script
                writes, so a file the user put there is refused, not overwritten):
                refuse symlinks
                anywhere under the source or under an existing staged copy,
                refuse a mountpoint at or under the selected source or
                destination root (an ordinary ancestor mount is normal and is
                not refused; unreadable mountinfo fails closed),
                refuse a destination inside/equal to the source or one this
                script did not create, refuse ANY content at a generated-output
                path unless the owner marker recorded this script writing that
                file for this source and it still hashes to the recorded value,
                create every output exclusively (O_EXCL|O_NOFOLLOW, no
                overwrite fallback) so an entry appearing between the check and
                the write fails instead of being written over,
                refuse to replace an existing staging
                that differs (a new owned --dest instead; this script never
                removes a staging or its outputs), hash the originals
                (`originals.sha256`, `sha256sum -c` compatible) plus a
                size/mtime inventory of EVERY original file, copy only the
                files upstream reads (CONTCAR, OSZICAR; `--all-files` for
                everything), re-hash the copy, and emit
                `stage_preprocess.py` + `run_stage.sh` (the rerunnable unit
                that calls upstream under a catbench-bearing interpreter).
                Nothing is executed here.
  3. verify   — re-hash the originals against `originals.sha256` and the
                inventory: unchanged originals are a verification item.

Usage:
  python3 scripts/catbench_vasp_stage.py scan   --source <originals> --out <stage>
  python3 scripts/catbench_vasp_stage.py stage  --source <originals> --dest <stage> \\
          --dataset-name my_dataset --coeff <stage>/coeff_setting.json --python <env>/bin/python
  python3 scripts/catbench_vasp_stage.py verify --source <originals> --dest <stage>
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import shlex
import shutil
import stat
import sys
from pathlib import Path

NEEDED_FILES = ("CONTCAR", "OSZICAR")
OWNER_MARKER = ".omm_stage_owner.json"
_GEN = "# generated by scripts/catbench_vasp_stage.py -- rerun this file to reproduce the staging conversion"
MOUNTINFO_PATH = "/proc/self/mountinfo"
# The files `stage` itself writes under <dest>. Each is checked BEFORE any write
# for a symlink/escape and for pre-existing content the owner record does not
# name as this script's own (the marker itself proves ownership, so it is not
# one of the recorded entries).
GENERATED_OUTPUTS = ("coeff_setting.json", "mapping_proposal.json", "originals.sha256",
                     "originals.inventory.json", "stage_preprocess.py", "run_stage.sh",
                     "stage_record.json", OWNER_MARKER)
RECORDED_OUTPUTS = tuple(n for n in GENERATED_OUTPUTS if n != OWNER_MARKER)
SCAN_OUTPUTS = ("scan.json", "mapping_proposal.json")
# dataset_name becomes `<dest>/<dataset_name>/` and `raw_data/<dataset_name>_adsorption.json`
# (upstream io_utils.get_raw_data_path builds the latter from cwd): a plain name only.
_DATASET_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
# Problems that make the upstream conversion fail or read a missing DFT result:
# staging refuses on them instead of handing upstream a tree it cannot convert.
BLOCKING_ISSUES = ("missing_slab", "oszicar_without_E0", "gas_key_without_gas_suffix")


def utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


# ── exclusive creation ───────────────────────────────────────────────────────
class ExclusiveCreateFailed(Exception):
    """Something was already at a path this script was about to create. It is
    never retried, never followed and never written over: an entry that appeared
    between the ownership check and the write means the call refuses instead."""

    def __init__(self, path: Path, exc: BaseException) -> None:
        super().__init__(f"{path}: {type(exc).__name__}: {exc}")
        self.path, self.error = Path(path), f"{type(exc).__name__}: {exc}"


def open_exclusive(path: Path, mode: int = 0o644) -> int:
    """The single create point for every file this script writes. O_EXCL makes a
    file that appeared since the check fail the create, O_NOFOLLOW makes a symlink
    planted there fail it too, and there is no overwrite fallback anywhere. A
    module-level seam: tests plant an entry inside it to exercise that race."""
    try:
        return os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    except OSError as exc:
        raise ExclusiveCreateFailed(path, exc) from None


def write_exclusive(path: Path, text: str, mode: int = 0o644) -> str:
    """Create `path` exclusively and write `text`; returns its sha256 so the owner
    record names exactly the bytes that landed."""
    with os.fdopen(open_exclusive(path, mode), "wb") as fh:
        os.fchmod(fh.fileno(), mode)         # the umask must not decide run_stage.sh's mode
        fh.write(text.encode())
    return sha256_text(text)


def mkdir_exclusive(path: Path) -> None:
    """os.mkdir fails if anything is already there, a symlink included."""
    try:
        os.mkdir(path)
    except OSError as exc:
        raise ExclusiveCreateFailed(path, exc) from None


def _mkdir_chain(root: Path, directory: Path, made: set) -> None:
    """Create each missing component of `directory` under `root` exclusively and
    once. Only components this call itself made are reused."""
    p = root
    for part in directory.relative_to(root).parts:
        p = p / part
        if p not in made:
            mkdir_exclusive(p)
            made.add(p)


# ── scan ─────────────────────────────────────────────────────────────────────
def _oszicar_has_e0(path: Path) -> bool:
    """Integrity evidence only: upstream parses `E0=` from the LAST line
    (vasp.py:read_E0_from_OSZICAR). No energy is read or stored here."""
    try:
        lines = path.read_text(errors="replace").splitlines()
    except OSError:
        return False
    return bool(lines) and "E0=" in lines[-1]


def _relaxation_converged(path: Path) -> bool | None:
    """Did this ionic relaxation converge?

    None when the question does not apply (no OUTCAR, or NSW <= 0: a single
    point has no ionic convergence to reach). Otherwise True when VASP printed
    "reached required accuracy". An unconverged run's last ionic step still
    parses as an energy, so without this an unfinished relaxation becomes a
    reference energy and shifts every adsorption energy built on it."""
    try:
        with open(path, "rb") as fh:
            head = fh.read(200_000).decode("utf-8", "replace")
            fh.seek(0, os.SEEK_END)
            size = fh.tell()
            fh.seek(max(0, size - 200_000))          # the marker is printed at the end
            tail = fh.read().decode("utf-8", "replace")
    except OSError:
        return None
    match = re.search(r"NSW\s*=\s*(\d+)", head)
    if not match or int(match.group(1)) <= 0:
        return None
    return "reached required accuracy" in tail


def scan(source: Path) -> dict:
    """Walk without following symlinks. Every symlink met is recorded; a
    later `stage` refuses when the list is non-empty."""
    source = Path(source).resolve()
    if not source.is_dir():
        raise FileNotFoundError(f"source is not a directory: {source}")
    pairs, incomplete, symlinks = [], [], []
    for dirpath, dirnames, filenames in os.walk(source, followlinks=False):
        rel = os.path.relpath(dirpath, source)
        for d in list(dirnames):
            if os.path.islink(os.path.join(dirpath, d)):
                symlinks.append(os.path.normpath(os.path.join(rel, d)))
                dirnames.remove(d)   # never descend through a link
        for f in filenames:
            if os.path.islink(os.path.join(dirpath, f)):
                symlinks.append(os.path.normpath(os.path.join(rel, f)))
        present = {f for f in NEEDED_FILES if f in filenames and not os.path.islink(os.path.join(dirpath, f))}
        if present == set(NEEDED_FILES):
            pairs.append({"dir": os.path.normpath(rel),
                          "oszicar_has_E0": _oszicar_has_e0(Path(dirpath) / "OSZICAR"),
                          "relaxation_converged": _relaxation_converged(Path(dirpath) / "OUTCAR")})
        elif present:
            incomplete.append({"dir": os.path.normpath(rel), "present": sorted(present),
                               "missing": sorted(set(NEEDED_FILES) - present)})
    return {"source": str(source), "scanned_utc": utc_now(), "pairs": sorted(pairs, key=lambda p: p["dir"]),
            "incomplete": sorted(incomplete, key=lambda p: p["dir"]), "symlinks": sorted(symlinks)}


def propose_mapping(scan_result: dict) -> dict:
    """Classify pairs by the upstream layout (vasp.py:269-287): `gas/<Xgas>/`,
    `<system>/slab/`, `<system>/<rxn>/[deeper]`. Gas coefficients are NOT
    proposed: each reaction lists the gas references that exist and asks."""
    gas, systems, unmapped = {}, {}, []
    for p in scan_result["pairs"]:
        parts = Path(p["dir"]).parts
        if len(parts) >= 2 and parts[0] == "gas":
            name = parts[1]
            gas[name] = {"dir": p["dir"], "key_ok": name.endswith("gas"), "oszicar_has_E0": p["oszicar_has_E0"]}
        elif len(parts) >= 2:
            sysname, rxn = parts[0], parts[1]
            entry = systems.setdefault(sysname, {"slab": None, "reactions": []})
            if rxn == "slab":
                entry["slab"] = {"dir": p["dir"], "oszicar_has_E0": p["oszicar_has_E0"]}
            else:
                entry["reactions"].append({"name": rxn, "dir": p["dir"], "depth": len(parts),
                                           "oszicar_has_E0": p["oszicar_has_E0"]})
        else:
            unmapped.append(p["dir"])   # a pair at the root: no system/reaction to attach to
    reactions, problems = {}, []
    for sysname, entry in sorted(systems.items()):
        if entry["slab"] is None:
            problems.append({"system": sysname, "issue": "missing_slab",
                             "detail": "no <system>/slab/{CONTCAR,OSZICAR}; the DFT result is missing — report, never compute"})
        for r in entry["reactions"]:
            rx = reactions.setdefault(r["name"], {
                "coeff": {"slab": -1, "adslab": 1},
                "gas_terms": "NEEDS_CONFIRMATION",
                "gas_candidates": sorted(k for k, g in gas.items() if g["key_ok"]),
                "systems": [],
            })
            if sysname not in rx["systems"]:      # one system may hold several sites of the same reaction
                rx["systems"].append(sysname)
    for name, g in gas.items():
        if not g["key_ok"]:
            problems.append({"gas": name, "issue": "gas_key_without_gas_suffix",
                             "detail": "upstream requires gas coefficient keys to end in 'gas' (vasp.py:248-257); rename the directory or confirm"})
    if reactions and not gas:
        problems.append({"issue": "missing_gas_reference", "detail": "no gas/<Xgas>/ pair found; every reaction needs its gas references confirmed or supplied"})
    for p in scan_result["incomplete"]:
        problems.append({"dir": p["dir"], "issue": "incomplete_pair", "detail": f"missing {p['missing']} — missing DFT result, reported not invented"})
    for p in scan_result["pairs"]:
        if not p["oszicar_has_E0"]:
            problems.append({"dir": p["dir"], "issue": "oszicar_without_E0", "detail": "last OSZICAR line has no E0= (upstream will fail to parse)"})
        if p.get("relaxation_converged") is False:
            problems.append({"dir": p["dir"], "issue": "unconverged_relaxation",
                             "detail": "OUTCAR has NSW > 0 but never printed 'reached required accuracy': this "
                                       "relaxation stopped at the step limit. Its last step still parses as an "
                                       "energy, so it would become a reference as-is -- reported, never corrected here"})
    return {
        "convention": "E_ads = 1*adslab - 1*slab - sum(coeff_gas * gas); slab/adslab keys fixed by upstream (vasp.py:241-247)",
        "gas_references": gas, "systems": systems, "reactions": reactions,
        "unmapped": unmapped, "problems": problems, "symlinks": scan_result["symlinks"],
        "ask": [f"reaction {n!r}: confirm gas terms from candidates {r['gas_candidates']}" for n, r in reactions.items()]
               + [f"{p.get('system') or p.get('gas') or p.get('dir', '')}: {p['issue']}" for p in problems],
        "status": "needs_confirmation" if reactions else "no_reactions_found",
    }


# ── coefficient check (mirrors upstream _validate_vasp_inputs + existence) ───
def validate_coeff(coeff_setting: dict, proposal: dict) -> list[str]:
    errors = []
    if not isinstance(coeff_setting, dict) or not coeff_setting:
        return ["coeff_setting must be a non-empty dict"]
    for rxn, coeffs in coeff_setting.items():
        if not isinstance(coeffs, dict):
            errors.append(f"{rxn}: not a dict"); continue
        if rxn not in proposal["reactions"]:
            errors.append(f"{rxn}: no scanned reaction directory named {rxn!r}")
        missing = {"slab", "adslab"} - set(coeffs)
        if missing:
            errors.append(f"{rxn}: missing required keys {sorted(missing)}")
        for key, val in coeffs.items():
            if isinstance(val, bool) or not isinstance(val, (int, float)) or val != val or val in (float("inf"), float("-inf")):
                errors.append(f"{rxn}: coefficient {key!r} is not a finite number")
            if key in ("slab", "adslab"):
                continue
            if not key.endswith("gas"):
                errors.append(f"{rxn}: gas key {key!r} must end with 'gas'")
            elif key not in proposal["gas_references"]:
                errors.append(f"{rxn}: gas reference {key!r} has no gas/{key}/{{CONTCAR,OSZICAR}} in the scan")
    return errors


def coeff_warnings(coeff_setting: dict) -> list[str]:
    """Not errors -- upstream accepts these -- but the sign that silently ruins
    a dataset. Upstream sums `energy_ref * stoi`, and the convention subtracts
    the gas terms the adsorbate is made from, so "H2gas": 0.5 instead of -0.5
    shifts every adsorption energy in that reaction. A positive term is right
    for a gas the reaction releases (OH* = adslab - slab - H2O + 1/2 H2), so it
    is flagged only when no gas term in that reaction is consumed."""
    out = []
    for rxn, coeffs in (coeff_setting or {}).items():
        if not isinstance(coeffs, dict):
            continue
        gas = {k: v for k, v in coeffs.items()
               if k not in ("slab", "adslab") and isinstance(v, (int, float)) and not isinstance(v, bool)}
        if any(v < 0 for v in gas.values()):
            continue
        for key, val in gas.items():
            if val > 0:
                out.append(f"{rxn}: gas coefficient {key!r} is positive ({val}) and no gas term is consumed; "
                           f"the convention subtracts the gas the adsorbate is made from, so this is usually "
                           f"{-val}. Confirm the sign before staging.")
    return out


def blocking_problems(proposal: dict, coeff_setting: dict) -> list[dict]:
    """Problems that stop staging: a used system without its slab, an OSZICAR
    upstream cannot parse, a gas directory whose key upstream would reject.
    Incomplete pairs elsewhere in the tree are reported, not blocking."""
    used_systems = {s for rxn in coeff_setting for s in proposal["reactions"].get(rxn, {}).get("systems", [])}
    out = []
    for p in proposal["problems"]:
        if p["issue"] not in BLOCKING_ISSUES:
            continue
        if p["issue"] == "missing_slab" and p.get("system") not in used_systems:
            continue
        out.append(p)
    return out


# ── hashing / inventory ──────────────────────────────────────────────────────
def _iter_files(root: Path, only: tuple[str, ...] | None):
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        dirnames[:] = [d for d in dirnames if not os.path.islink(os.path.join(dirpath, d))]
        for f in sorted(filenames):
            p = Path(dirpath) / f
            if p.is_symlink():
                continue
            if only is None or f in only:
                yield p


def manifest_text(hashes: dict[str, str]) -> str:
    """`<sha256>  ./<relpath>` lines, sorted — `(cd root && sha256sum -c)` works.
    Built in memory: the bytes are known before the file is created exclusively."""
    lines = sorted(f"{digest}  {rel}" for rel, digest in hashes.items())
    return "\n".join(lines) + ("\n" if lines else "")


def read_manifest(path: Path) -> dict[str, str]:
    out = {}
    for ln in path.read_text().splitlines():
        if ln.strip():
            digest, rel = ln.split("  ", 1)
            out[rel] = digest
    return out


def inventory(root: Path) -> dict[str, dict]:
    """size + mtime_ns of EVERY original file (no hashing of multi-GB outputs)."""
    return {("./" + p.relative_to(root).as_posix()): {"size": p.stat().st_size, "mtime_ns": p.stat().st_mtime_ns}
            for p in _iter_files(root, None)}


def check_manifest(root: Path, manifest: dict[str, str]) -> dict:
    changed, missing = [], []
    for rel, digest in manifest.items():
        p = root / rel
        if not p.is_file():
            missing.append(rel)
        elif sha256_file(p) != digest:
            changed.append(rel)
    return {"unchanged": not changed and not missing, "changed": changed, "missing": missing, "checked": len(manifest)}


# ── mount boundaries ─────────────────────────────────────────────────────────
def read_mountinfo() -> str:
    """Raw /proc/self/mountinfo text. A module-level seam: tests substitute
    synthetic text, so nothing is ever mounted to exercise the refusals."""
    return Path(MOUNTINFO_PATH).read_text()


def _unescape_mountinfo(field: str) -> str:
    """mountinfo octal-escapes space, tab, newline and backslash in paths."""
    out, i = [], 0
    while i < len(field):
        if field[i] == "\\" and i + 3 < len(field) and all(c in "01234567" for c in field[i + 1:i + 4]):
            out.append(chr(int(field[i + 1:i + 4], 8))); i += 4
        else:
            out.append(field[i]); i += 1
    return "".join(out)


def parse_mountpoints(text: str) -> list[str]:
    """Mount points (field 5, after a variable number of optional fields ended
    by ` - `). Anything unparseable RAISES: the caller fails closed rather than
    stage while guessing where the mount boundaries are."""
    points = []
    for ln in text.splitlines():
        if not ln.strip():
            continue
        fields = ln.split(" ")
        try:
            sep = fields.index("-", 6)          # optional fields sit between 6 and the separator
        except ValueError:
            raise ValueError(f"no ' - ' separator in mountinfo line: {ln!r}") from None
        if len(fields) - sep < 4 or not fields[4].startswith("/"):
            raise ValueError(f"malformed mountinfo line: {ln!r}")
        points.append(_unescape_mountinfo(fields[4]))
    return points


def _mount_message(what: str, root: Path, point: Path) -> str:
    where = "is itself a mountpoint" if point == root else f"holds the mountpoint {point}"
    return (f"{what} {root} {where}: a mounted tree is unsupported by this staging recipe "
            "(this says nothing about the data, which may be perfectly fine) — select a root with no mount at "
            "or under it, or copy the tree onto a single filesystem first and stage that copy")


def _device_crossings(root: Path, what: str, pinned: int) -> list[str]:
    """st_dev pinned to the selected root: an entry on another device below it is
    a mount boundary even if mountinfo never named it. Never traversed."""
    out = []
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        for name in list(dirnames) + filenames:
            q = os.path.join(dirpath, name)
            if os.path.islink(q):
                if name in dirnames:
                    dirnames.remove(name)       # links are refused elsewhere; never followed here
                continue
            try:
                dev = os.lstat(q).st_dev
            except OSError as exc:
                out.append(f"{what} entry {q} cannot be stat'ed ({exc}); refusing rather than stage past it")
                if name in dirnames:
                    dirnames.remove(name)
                continue
            if dev != pinned:
                out.append(_mount_message(what, Path(root), Path(q)))
                if name in dirnames:
                    dirnames.remove(name)       # a mounted subtree is not walked
    return out


def _mount_refusals(roots: tuple[tuple[str, Path], ...]) -> dict | None:
    """Hard refusal for a mountpoint AT or nested UNDER a selected root. An
    ordinary ancestor mount (/ itself, a workspace on a mounted filesystem) is
    the normal case and is never refused. st_dev alone would miss a same-device
    bind mount, so mountinfo is parsed too — and if it cannot be read or parsed
    this fails closed."""
    try:
        points = [Path(m) for m in parse_mountpoints(read_mountinfo())]
    except (OSError, ValueError) as exc:
        return {"reason": "mountinfo_unavailable",
                "detail": f"{MOUNTINFO_PATH} could not be read or parsed ({type(exc).__name__}: {exc}); "
                          "refusing rather than stage without knowing where the mount boundaries are"}
    errors, mounts = [], []
    for what, root in roots:
        root = Path(root)
        pinned = None
        if root.is_dir() and not root.is_symlink():
            try:
                pinned = os.lstat(root).st_dev
            except OSError as exc:
                errors.append(f"{what} {root} cannot be stat'ed ({exc}); refusing rather than stage past it")
        for m in points:
            if m == root or root in m.parents:  # AT or nested UNDER; ancestors are fine
                mounts.append(str(m))
                errors.append(_mount_message(what, root, m))
        if pinned is not None:
            errors.extend(_device_crossings(root, what, pinned))
    if errors:
        return {"reason": "mounted_tree_unsupported", "mounts": sorted(set(mounts)),
                "errors": list(dict.fromkeys(errors)),   # mountinfo and the st_dev pin agree on nested mounts
                "detail": "a mounted tree at or under a selected root is unsupported by this staging recipe; "
                          "nothing was read through it, nothing was written and nothing was removed"}
    return None


# ── stage ────────────────────────────────────────────────────────────────────
def _root_symlink(path: Path, what: str) -> str | None:
    """The source/destination roots (and every ancestor) are checked BEFORE
    resolving: a link at the root would otherwise vanish into `resolve()`."""
    p = Path(path)
    for q in (p, *p.parents):
        if q.is_symlink():
            return f"{what} {p} passes through a symlink at {q} (refused; give the real path explicitly)"
    return None


def _identity_sha256(rec: dict) -> str:
    """sha256 over the marker's identity fields only: which script wrote it, for
    which resolved source, under which record id. The recorded output hashes are
    the ownership evidence; this catches a marker whose identity was edited."""
    return sha256_text(json.dumps({k: rec.get(k) for k in ("created_by", "source", "record_id")}, sort_keys=True))


def _owner_ok(dest: Path, source: Path) -> str | None:
    """A non-empty destination is accepted only when this script created it
    FOR THIS SOURCE (marker names the same resolved source) and the marker still
    carries the output record that is the sole proof of what this script wrote."""
    marker = dest / OWNER_MARKER
    if not marker.is_file() or marker.is_symlink():
        return f"destination {dest} is non-empty and was not created by this script (no {OWNER_MARKER}); refusing to write into a directory it does not own"
    try:
        rec = json.loads(marker.read_text())
    except ValueError:
        return f"{marker} is unreadable; refusing"
    if not isinstance(rec, dict):
        return f"{marker} is unreadable; refusing"
    if rec.get("created_by") != "scripts/catbench_vasp_stage.py" or rec.get("source") != str(source):
        return f"{marker} names source {rec.get('source')!r}, not {str(source)!r}; refusing to mix stagings"
    if not rec.get("record_id") or not isinstance(rec.get("outputs"), dict):
        return (f"{marker} carries no recorded output hashes; refusing to write into a destination whose contents "
                "this script cannot prove it wrote (give a new owned --dest)")
    if rec.get("identity_sha256") != _identity_sha256(rec):
        return f"{marker} identity does not match the record it carries; refusing"
    return None


def _owner_record(dest: Path) -> dict | None:
    """The marker's record, or None when there is none to read (a fresh dest).
    `_owner_ok` has already refused a marker that is a link, unparseable, names
    another source or carries no output record, so what comes back is usable."""
    marker = dest / OWNER_MARKER
    if marker.is_symlink() or not marker.is_file():
        return None
    try:
        rec = json.loads(marker.read_text())
    except (OSError, ValueError):
        return None
    return rec if isinstance(rec, dict) and isinstance(rec.get("outputs"), dict) else None


def _check_destination(source: Path, dest: Path) -> list[str]:
    errors = []
    for what, p in (("source", source), ("destination", dest)):
        if (m := _root_symlink(p, what)):
            errors.append(m)
    src, dst = source.resolve(), dest.resolve()
    if dst == src:
        errors.append("destination equals the source")
    if src in dst.parents:
        errors.append(f"destination {dst} lies inside the source {src}")
    if dst in src.parents:
        errors.append(f"source {src} lies inside the destination {dst}")
    if dst.exists():
        if not dst.is_dir():
            errors.append(f"destination exists and is not a directory: {dst}")
        elif any(dst.iterdir()) and (m := _owner_ok(dst, src)):
            errors.append(m)
    return errors


def _write_owner_marker(dest: Path, source: Path) -> dict:
    """Created EXCLUSIVELY on first use: anything already at that path fails the
    create instead of being replaced. The record starts with no outputs; each
    command adds the sha256 of what it actually wrote."""
    rec = {"created_by": "scripts/catbench_vasp_stage.py", "source": str(source),
           "record_id": os.urandom(16).hex(), "utc": utc_now(), "outputs": {}}
    rec["identity_sha256"] = _identity_sha256(rec)
    write_exclusive(dest / OWNER_MARKER, json.dumps(rec, indent=2) + "\n")
    return rec


def _update_owner_marker(dest: Path, rec: dict, written: dict[str, str]) -> None:
    """Never an in-place overwrite: the merged record is created exclusively under
    a temp name and renamed onto the marker in one step, so a marker swapped since
    it was read is replaced whole, never appended to."""
    merged = {**rec, "outputs": {**rec.get("outputs", {}), **written}, "utc": utc_now()}
    merged["identity_sha256"] = _identity_sha256(merged)
    tmp = dest / f"{OWNER_MARKER}.new.{os.getpid()}"
    write_exclusive(tmp, json.dumps(merged, indent=2) + "\n")
    os.replace(tmp, dest / OWNER_MARKER)


def _render_preprocess_py(dataset_name: str, catbench_version: str | None = None) -> str:
    guard = ""
    if catbench_version:
        guard = (f"if catbench.__version__ != {catbench_version!r}:\n"
                 f"    sys.stderr.write('[stop] approved catbench {catbench_version} but this env has ' + catbench.__version__ + '\\n')\n"
                 f"    sys.exit(3)\n")
    return f'''{_GEN}
import json, sys
from pathlib import Path
import catbench
{guard}from catbench.adsorption import vasp_preprocessing
from catbench.utils.data_utils import load_catbench_json

here = Path(__file__).resolve().parent
coeff_setting = json.loads((here / "coeff_setting.json").read_text())
vasp_preprocessing({dataset_name!r}, coeff_setting)          # upstream: cleanup (on the COPY) + convert -> raw_data/
out = here / "raw_data" / "{dataset_name}_adsorption.json"
data = load_catbench_json(str(out))                           # the JSON must load under the pinned catbench
record = {{"dataset": {dataset_name!r}, "raw_data": str(out), "n_reactions": len(data),
          "catbench_version": catbench.__version__, "python": sys.executable}}
(here / "stage_result.json").write_text(json.dumps(record, indent=2) + "\\n")
print(json.dumps(record))
'''


def _render_run_sh(dest: Path, python: str) -> str:
    return "\n".join(["#!/bin/sh", _GEN, "set -eu", f"cd {shlex.quote(str(dest))}",
                      f"exec {shlex.quote(str(python))} {shlex.quote(str(dest / 'stage_preprocess.py'))}"]) + "\n"


def _tree_hashes(root: Path) -> dict[str, str]:
    """`./<rel>` -> sha256 for EVERY regular file under root. Callers check
    `_tree_symlinks` first: a link here is refused, never silently skipped."""
    return {("./" + p.relative_to(root).as_posix()): sha256_file(p) for p in _iter_files(root, None)} if root.is_dir() else {}


def _tree_symlinks(root: Path) -> list[str]:
    """Every symlink anywhere under root, relative and sorted. A staged copy
    tree must hold none: upstream DELETES inside the tree it is given, so a link
    there would reach whatever it points at."""
    out = []
    if not root.is_dir() or root.is_symlink():
        return out
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        rel = os.path.relpath(dirpath, root)
        for name in list(dirnames) + filenames:
            if os.path.islink(os.path.join(dirpath, name)):
                out.append(os.path.normpath(os.path.join(rel, name)))
                if name in dirnames:
                    dirnames.remove(name)       # never descend through a link
    return sorted(out)


def copy_file(src: Path, dst: Path) -> None:
    """The single copy point (a real file copy, never a link), so a failing
    copy can be exercised without a failing filesystem. The destination is
    created exclusively: anything appearing under the temp tree since it was
    made fails the copy instead of being written through."""
    with os.fdopen(open_exclusive(dst), "wb") as out, src.open("rb") as fh:
        shutil.copyfileobj(fh, out)
    shutil.copystat(src, dst)


def _diff_trees(planned: dict[str, str], actual: dict[str, str]) -> dict:
    return {"extras": sorted(k for k in actual if k not in planned),
            "missing": sorted(k for k in planned if k not in actual),
            "changed": sorted(k for k in planned if k in actual and planned[k] != actual[k])}


def _inside_dest_not_link(path: Path, dest: Path, what: str) -> str | None:
    """Every path this script writes, renames or removes under dest must be a
    plain entry of the owned dest: not a symlink (or under one) and, once
    resolved, still inside dest. Nothing outside the owned tree is touched."""
    p = Path(path)
    for q in (p, *p.parents):
        if q == dest:
            break
        if q.is_symlink():
            return f"{what} {p} passes through a symlink at {q}; refusing (nothing under {dest} may point elsewhere)"
    if p.exists():
        r = p.resolve()
        if dest not in r.parents:
            return f"{what} {p} resolves to {r}, outside the owned destination {dest}; refusing"
    return None


def _unowned_outputs(dest: Path, record: dict | None, names: tuple[str, ...]) -> list[dict]:
    """Ownership is a RECORD, not a shape. A file already sitting where this call
    writes is accepted only when the owner marker records this script writing that
    name for this source AND the file still hashes to the recorded value. Valid
    JSON, a well-formed manifest or a generated-by marker prove nothing about who
    wrote a file, so no content is inspected here — no record, a missing entry, a
    drifted hash, a symlink or a non-regular entry all refuse."""
    recorded = (record or {}).get("outputs") or {}
    out = []
    for name in names:
        p = dest / name
        try:
            st_mode = os.lstat(p).st_mode
        except OSError:
            continue                        # nothing there: it will be created exclusively
        if stat.S_ISLNK(st_mode):
            out.append({"path": str(p), "error": f"{p} exists and is a symlink; refusing to write over it"})
        elif not stat.S_ISREG(st_mode):
            out.append({"path": str(p), "error": f"{p} exists and is not a regular file; refusing to write over it"})
        elif name not in recorded:
            out.append({"path": str(p), "error": f"{p} exists and no {OWNER_MARKER} record says this script wrote it; "
                                                 "refusing to write over content it does not own"})
        else:
            try:
                digest = sha256_file(p)
            except OSError as exc:
                out.append({"path": str(p), "error": f"{p} exists and cannot be read ({exc}); refusing to write over it"})
                continue
            if digest != recorded[name]:
                out.append({"path": str(p), "error": f"{p} exists but hashes to {digest}, not the {recorded[name]} this "
                                                     "script recorded writing; refusing to write over content that changed since"})
    return out


def _outputs_to_write(dest: Path, record: dict | None, planned: dict[str, str]) -> tuple[dict[str, str], list[dict]]:
    """Split the planned outputs into the ones to create and the owned ones this
    call would change. An owned output whose bytes this call reproduces exactly is
    KEPT, never rewritten; one that would change is refused, because this script
    overwrites nothing — a new owned --dest is the remedy."""
    recorded = (record or {}).get("outputs") or {}
    to_create, differs = {}, []
    for name, text in planned.items():
        p = dest / name
        if not p.exists():
            to_create[name] = text
        elif sha256_text(text) != recorded.get(name):
            differs.append({"path": str(p), "error": f"{p} holds this script's earlier output and this call would write "
                                                     "different content there; refusing to overwrite it"})
    return to_create, differs


def stage(source: Path, dest: Path, dataset_name: str, coeff_setting: dict, python: str,
          *, all_files: bool = False, catbench_version: str | None = None) -> dict:
    """Copy the needed originals into an owned destination and write the
    rerunnable conversion unit. The staged copy tree `<dest>/<dataset_name>`
    must equal the planned file set EXACTLY (no extras, nothing missing,
    same hashes): a fresh staging is copied into a temp dir inside dest,
    validated, then renamed into place; an existing identical copy tree is
    kept as is; an existing copy tree that differs from the plan (files
    removed from the source since, edits, strays), a symlink anywhere under
    it, a leftover temp dir, or previous outputs without their copy tree are
    REFUSED — nothing is removed or replaced by this script; the user gives a
    new owned --dest. A copy that fails part way RETAINS its temp tree and
    names it. Originals are never written.

    Generated outputs are owned by RECORD: the owner marker holds the sha256 of
    every file this script wrote for this source, and a file already at one of
    those paths is only accepted when the record names it and it still hashes to
    the recorded value. An owned output whose bytes this call would reproduce is
    kept untouched; one that would change is refused (`owned_outputs_differ`)
    rather than overwritten, so `stage_record.json` on a reused staging stays the
    one the first run wrote — the fresh record is returned and printed only.
    Everything is created with O_EXCL|O_NOFOLLOW, so an entry planted between the
    check and the write fails the create (`exclusive_create_failed`) instead of
    being written over."""
    if not _DATASET_NAME_RE.match(dataset_name or ""):
        return {"ok": False, "reason": "dataset_name_invalid",
                "detail": f"{dataset_name!r} must match {_DATASET_NAME_RE.pattern} (it names a directory and the raw_data JSON)"}
    derrs = _check_destination(Path(source), Path(dest))     # root symlinks checked before resolve()
    if derrs:
        return {"ok": False, "reason": "destination_refused", "errors": derrs}
    source, dest = Path(source).resolve(), Path(dest).resolve()
    if (mr := _mount_refusals((("source", source), ("destination", dest)))):
        return {"ok": False, **mr}               # refused before the tree is walked, let alone written
    sc = scan(source)
    if sc["symlinks"]:
        return {"ok": False, "reason": "symlinks_in_source", "symlinks": sc["symlinks"],
                "detail": "staging refuses to traverse symlinks (a link tree into the originals would be cleaned in place); "
                          "resolve or exclude them explicitly and rerun"}
    proposal = propose_mapping(sc)
    errs = validate_coeff(coeff_setting, proposal)
    if errs:
        return {"ok": False, "reason": "coeff_setting_invalid", "errors": errs}
    blocking = blocking_problems(proposal, coeff_setting)
    if blocking:
        return {"ok": False, "reason": "missing_dft_results", "problems": blocking,
                "detail": "a DFT result upstream needs is missing or unparseable; it is reported, never computed or invented"}

    only = None if all_files else NEEDED_FILES
    planned = {("./" + p.relative_to(source).as_posix()): sha256_file(p) for p in _iter_files(source, only)}
    copy_root = dest / dataset_name
    tmp_root = dest / f".{dataset_name}.staging.tmp"
    previous_outputs = [p for p in (dest / "raw_data", dest / "stage_result.json") if p.exists() or p.is_symlink()]
    # every entry under dest that this call would read/rename/create/write is checked for a symlink escape first
    watched = [("copy tree", copy_root), ("temp dir", tmp_root), ("raw_data", dest / "raw_data"),
               ("stage_result.json", dest / "stage_result.json")] + [(n, dest / n) for n in GENERATED_OUTPUTS]
    escapes = [m for what, p in watched if dest.exists() and (m := _inside_dest_not_link(p, dest, what))]
    if escapes:
        return {"ok": False, "reason": "destination_refused", "errors": escapes}
    owner = _owner_record(dest)                 # the sole ownership evidence: what this script recorded writing
    unrelated = _unowned_outputs(dest, owner, RECORDED_OUTPUTS)
    if copy_root.exists() and not copy_root.is_dir():
        unrelated.append({"path": str(copy_root), "error": f"{copy_root} exists and is not a directory; refusing to write over it"})
    if unrelated:
        return {"ok": False, "reason": "unrelated_destination_content", "paths": [u["path"] for u in unrelated],
                "errors": [u["error"] for u in unrelated],
                "detail": "something this call would write already exists at that path and no owner record proves this "
                          "script wrote it for this source; nothing was written or removed. Give a new owned --dest"}
    if tmp_root.exists():                       # leftover of an aborted attempt, or something else with that name: not ours to remove
        return {"ok": False, "reason": "staging_tmp_exists",
                "detail": f"{tmp_root} already exists; nothing was written. Inspect and remove it yourself, or give a new owned --dest"}
    reused = False
    if copy_root.exists():                      # re-stage into an owned destination
        if (links := _tree_symlinks(copy_root)):
            return {"ok": False, "reason": "symlinks_in_staged_tree", "symlinks": [str(copy_root / ln) for ln in links],
                    "detail": f"{copy_root} holds symlinks; a staged tree must be real files only (upstream deletes "
                              "inside the tree it is given, so a link would reach outside it). Nothing was written "
                              "or removed; give a new owned --dest"}
        diff = _diff_trees(planned, _tree_hashes(copy_root))
        if any(diff.values()):
            return {"ok": False, "reason": "staged_tree_differs", "staged_diff": diff,
                    "previous_outputs": [str(p) for p in previous_outputs],
                    "detail": f"{copy_root} already holds a staging that is not what the source would produce now; "
                              "nothing was written or removed. Give a new owned --dest (this script never replaces a staging)"}
        reused = True                           # identical copy tree already in place: keep it, copy nothing
    elif previous_outputs:
        return {"ok": False, "reason": "stale_outputs_without_copy_tree",
                "previous_outputs": [str(p) for p in previous_outputs],
                "detail": f"{dest} holds outputs of an earlier run but no {copy_root}; nothing was written or removed. "
                          "Give a new owned --dest"}

    run_sh = dest / "run_stage.sh"
    # every output's bytes are known before anything is written: an owned one this
    # call would reproduce exactly is kept, one it would change is refused here
    outputs = {"coeff_setting.json": json.dumps(coeff_setting, indent=2, sort_keys=True) + "\n",
               "mapping_proposal.json": json.dumps(proposal, indent=2) + "\n",
               "originals.sha256": manifest_text(planned),
               "originals.inventory.json": json.dumps(inventory(source), indent=2, sort_keys=True) + "\n",
               "stage_preprocess.py": _render_preprocess_py(dataset_name, catbench_version),
               "run_stage.sh": _render_run_sh(dest, python)}
    to_create, differs = _outputs_to_write(dest, owner, outputs)
    if differs:
        return {"ok": False, "reason": "owned_outputs_differ", "paths": [d["path"] for d in differs],
                "errors": [d["error"] for d in differs],
                "detail": "this script wrote those files for this source but this call would produce different content; "
                          "nothing was written or removed (it never overwrites its own outputs either). Give a new owned --dest"}
    try:
        dest.mkdir(parents=True, exist_ok=True)
        if owner is None:
            owner = _write_owner_marker(dest, source)   # first use: created exclusively
        copied, written = 0, {}
        if not reused:
            # From here a write has begun. Anything that goes wrong RETAINS the temp
            # tree (never deleted here) and names it, so the user can inspect it; the
            # originals were only ever read, and a rerun refuses the leftover.
            mkdir_exclusive(tmp_root)
            made = {tmp_root}
            try:
                for rel in planned:
                    target = tmp_root / rel[2:]
                    _mkdir_chain(tmp_root, target.parent, made)
                    copy_file(source / rel[2:], target)  # a real file copy; never a link
                    copied += 1
                staged_hashes = _tree_hashes(tmp_root)
            except OSError as exc:
                return {"ok": False, "reason": "copy_failed", "retained_tmp": str(tmp_root), "copied_files": copied,
                        "error": f"{type(exc).__name__}: {exc}",
                        "detail": f"the copy into {tmp_root} failed part way; the partial copy is RETAINED for inspection "
                                  "and is never removed by this script (a rerun refuses it as staging_tmp_exists). "
                                  "The originals were only read, never written"}
            if (links := _tree_symlinks(tmp_root)):
                return {"ok": False, "reason": "symlinks_in_staged_tree", "retained_tmp": str(tmp_root),
                        "symlinks": [str(tmp_root / ln) for ln in links],
                        "detail": f"{tmp_root} holds symlinks; a staged tree must be real files only. It is RETAINED for "
                                  "inspection, nothing was renamed and nothing was removed"}
            staged_check = _diff_trees(planned, staged_hashes)
            if any(staged_check.values()):      # exact path set, extras included
                return {"ok": False, "reason": "staged_tree_mismatch", "staged_check": staged_check,
                        "retained_tmp": str(tmp_root),
                        "detail": f"the copy under {tmp_root} is not exactly the planned file set; it is RETAINED for "
                                  "inspection, nothing was renamed and nothing was removed"}
            if copy_root.exists() or copy_root.is_symlink():   # appeared since the check: the rename must not replace it
                raise ExclusiveCreateFailed(copy_root, FileExistsError(17, "File exists"))
            try:
                tmp_root.rename(copy_root)      # copy_root did not exist (checked above): a plain rename, nothing replaced
            except OSError as exc:
                return {"ok": False, "reason": "copy_failed", "retained_tmp": str(tmp_root), "copied_files": copied,
                        "error": f"{type(exc).__name__}: {exc}",
                        "detail": f"the validated copy could not be renamed to {copy_root}; it is RETAINED under "
                                  f"{tmp_root} and is never removed by this script. The originals were only read"}
        final_check = _diff_trees(planned, _tree_hashes(copy_root))
        if any(final_check.values()):
            return {"ok": False, "reason": "staged_tree_mismatch", "staged_check": final_check,
                    "detail": f"{copy_root} does not hold exactly the planned file set"}
        copy_check = check_manifest(copy_root, planned)
        if not copy_check["unchanged"]:
            return {"ok": False, "reason": "copy_hash_mismatch", "copy_check": copy_check}

        for name, text in outputs.items():      # owned-and-identical ones are not in to_create: they are kept as they are
            if name in to_create:
                written[name] = write_exclusive(dest / name, text, 0o755 if name == "run_stage.sh" else 0o644)
        record = {"ok": True, "source": str(source), "dest": str(dest), "dataset_name": dataset_name,
                  "copied_files": copied, "hashed_files": len(planned), "copied_subset": list(only) if only else "ALL",
                  "python": python, "catbench_version": catbench_version, "run": str(run_sh),
                  "expected_output": str(dest / "raw_data" / f"{dataset_name}_adsorption.json"),
                  "staged_tree_exact": True, "reused_identical_staging": reused,
                  "previous_outputs_kept": [str(p) for p in previous_outputs],
                  "problems": proposal["problems"], "warnings": coeff_warnings(coeff_setting),
                  "staged_utc": utc_now()}
        if not (dest / "stage_record.json").exists():   # an owned one is kept: it is never rewritten (see the docstring)
            written["stage_record.json"] = write_exclusive(dest / "stage_record.json", json.dumps(record, indent=2) + "\n")
        if written:
            _update_owner_marker(dest, owner, written)  # the record names the bytes that actually landed
        return record
    except ExclusiveCreateFailed as exc:
        return {"ok": False, "reason": "exclusive_create_failed", "path": str(exc.path), "error": exc.error,
                **({"retained_tmp": str(tmp_root)} if tmp_root.exists() else {}),
                "detail": f"{exc.path} could not be created exclusively: something is already there that was not there "
                          "when this call checked. Nothing was written over, nothing was renamed and nothing was "
                          "removed; inspect that path, then give a new owned --dest"}


def verify(source: Path, dest: Path) -> dict:
    source, dest = Path(source).resolve(), Path(dest).resolve()
    manifest = dest / "originals.sha256"
    inv_path = dest / "originals.inventory.json"
    if not manifest.is_file():
        return {"ok": False, "reason": f"no {manifest}"}
    hashes = check_manifest(source, read_manifest(manifest))
    inv_now = inventory(source)
    inv_then = json.loads(inv_path.read_text()) if inv_path.is_file() else {}
    inv_diff = {"missing": sorted(k for k in inv_then if k not in inv_now),
                "added": sorted(k for k in inv_now if k not in inv_then),
                "changed": sorted(k for k in inv_then if k in inv_now and inv_then[k] != inv_now[k])}
    symlinks = scan(source)["symlinks"]      # a link that appeared since staging is a change too
    ok = hashes["unchanged"] and not any(inv_diff.values()) and not symlinks
    return {"ok": ok, "hashes": hashes, "inventory_diff": inv_diff, "symlinks_now": symlinks, "verified_utc": utc_now()}


# ── CLI ──────────────────────────────────────────────────────────────────────
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("scan"); s.add_argument("--source", required=True); s.add_argument("--out", required=True)
    t = sub.add_parser("stage")
    t.add_argument("--source", required=True); t.add_argument("--dest", required=True)
    t.add_argument("--dataset-name", required=True); t.add_argument("--coeff", required=True)
    t.add_argument("--python", required=True, help="catbench-bearing interpreter that will run run_stage.sh")
    t.add_argument("--all-files", action="store_true", help="copy every file, not just CONTCAR/OSZICAR")
    t.add_argument("--catbench-version", default=None, help="approved catbench version: stage_preprocess.py refuses any other")
    v = sub.add_parser("verify"); v.add_argument("--source", required=True); v.add_argument("--dest", required=True)
    args = ap.parse_args(argv)

    if args.cmd == "scan":
        derrs = _check_destination(Path(args.source), Path(args.out))   # --out obeys the same containment/ownership rules
        if derrs:
            print(json.dumps({"ok": False, "reason": "out_refused", "errors": derrs}, indent=2))
            return 3
        if (mr := _mount_refusals((("source", Path(args.source).resolve()), ("out", Path(args.out).resolve())))):
            print(json.dumps({"ok": False, **mr}, indent=2))
            return 3
        sc = scan(Path(args.source))
        proposal = propose_mapping(sc)
        out = Path(args.out)
        outputs = {"scan.json": json.dumps(sc, indent=2) + "\n",
                   "mapping_proposal.json": json.dumps(proposal, indent=2) + "\n"}
        owner = _owner_record(out)          # `stage` and `scan` share one record of what this script wrote
        unrelated = _unowned_outputs(out, owner, SCAN_OUTPUTS)
        if unrelated:
            print(json.dumps({"ok": False, "reason": "unrelated_destination_content",
                              "paths": [u["path"] for u in unrelated], "errors": [u["error"] for u in unrelated],
                              "detail": "something this scan would write already exists at that path and no owner record "
                                        "proves this script wrote it for this source; nothing was written. Give a new --out"},
                             indent=2))
            return 3
        # scan.json carries the scan's own timestamp, so an owned one is KEPT rather
        # than compared (it is never rewritten either); the proposal is deterministic
        # and a re-scan that would change it is refused.
        to_create, differs = _outputs_to_write(out, owner, {"mapping_proposal.json": outputs["mapping_proposal.json"]})
        if differs:
            print(json.dumps({"ok": False, "reason": "owned_outputs_differ", "paths": [d["path"] for d in differs],
                              "errors": [d["error"] for d in differs],
                              "detail": "this script wrote those files for this source but this scan would produce "
                                        "different content; nothing was written or removed. Give a new --out"}, indent=2))
            return 3
        if not (out / "scan.json").exists():
            to_create["scan.json"] = outputs["scan.json"]
        try:
            out.mkdir(parents=True, exist_ok=True)
            if owner is None:
                owner = _write_owner_marker(out, Path(args.source).resolve())   # so a later `stage --dest <out>` is accepted
            written = {name: write_exclusive(out / name, text) for name, text in to_create.items()}
            if written:
                _update_owner_marker(out, owner, written)
        except ExclusiveCreateFailed as exc:
            print(json.dumps({"ok": False, "reason": "exclusive_create_failed", "path": str(exc.path), "error": exc.error,
                              "detail": f"{exc.path} could not be created exclusively: something is already there that "
                                        "was not there when this scan checked. Nothing was written over or removed"}, indent=2))
            return 3
        print(json.dumps({"pairs": len(sc["pairs"]), "incomplete": len(sc["incomplete"]), "symlinks": sc["symlinks"],
                          "reactions": sorted(proposal["reactions"]), "gas_references": sorted(proposal["gas_references"]),
                          "problems": proposal["problems"], "ask": proposal["ask"],
                          "wrote": [str(out / "scan.json"), str(out / "mapping_proposal.json")]}, indent=2))
        return 3 if sc["symlinks"] else 0
    if args.cmd == "stage":
        coeff = json.loads(Path(args.coeff).read_text())
        rec = stage(Path(args.source), Path(args.dest), args.dataset_name, coeff, args.python,
                    all_files=args.all_files, catbench_version=args.catbench_version)
        print(json.dumps(rec, indent=2))
        return 0 if rec["ok"] else 3
    rec = verify(Path(args.source), Path(args.dest))
    print(json.dumps(rec, indent=2))
    return 0 if rec["ok"] else 3


if __name__ == "__main__":
    sys.exit(main())
