#!/usr/bin/env python3
"""catbench_jobgen.py — templates + emitters for one catbench model job.

Owns the three things every catbench run needs on disk (Principle 2: "the
file is the action" — nothing executes that does not first exist as a file
the user can rerun byte-identically without Claude):

  1. `render_model_script`  — the per-model catbench python script, a verbatim
     `resolve()` codegen (absolute weight paths and all — see F13 in the
     consensus plan: 11/20 families ship absolute host weight paths, so a
     host-independence assertion on this file is impossible by construction
     and is deliberately NOT part of this module's test suite).
  2. `render_runner_sh`     — the AC7 unit. `env_run` (NequIP/DeePMD/DPA4) is
     an allow-listed dict applied to a SUBPROCESS environment by resolve();
     it never lived in the `.py` text, so the `.py` alone was never
     rerunnable for those three frameworks. This `.sh` exports it, `cd`s to
     the absolute benchmark workdir first (N4 — catbench writes into
     `cwd/result/`; without the `cd`, rerunning this file from elsewhere
     silently starts a fresh `result/`), then execs the `.py`.
  3. `render_slurm_sh`      — an SBATCH header followed by the IDENTICAL body
     as `render_runner_sh` (`_render_body`), so local and SLURM execution
     cannot drift into two emitters that disagree.

`emit()` writes all of the above under `<workdir>/jobs/`.

No GPU, no torch, no catbench import here — this whole module is GPU-free and
exercised directly by tests/test_catbench_jobgen.py.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

# The exact per-model catbench script. Runs INSIDE the model's own env
# interpreter (resolve()'s "python"), builds calc_num calculator instances
# from the registry's import+inference lines, and runs catbench's
# AdsorptionCalculation with config={mlip_name, benchmark} — the skeleton
# `run_examples/catbench_quickstart.py` has always used. Moved here verbatim
# so a SINGLE module owns catbench codegen (was `_build_script` in
# catbench_quickstart.py).
_CATBENCH_TEMPLATE = '''\
import warnings
warnings.filterwarnings("ignore")
from catbench.adsorption import AdsorptionCalculation
{d3_import}{import_lines}

calc_num = {calc_num}
calculators = []
print("Calculators Initializing...")
for i in range(calc_num):
    print(f"{{i}}th calculator")
{inference_lines}
{d3_apply}    calculators.append(calc)

config = {{"mlip_name": {mlip_name!r}, "benchmark": {benchmark!r}}}
AdsorptionCalculation(calculators, **config).run()
print("[catbench] {mlip_name} done")
'''

# Marks the generated runner unit's contract in one line, so a diff of the
# emitted file always states what it is even outside this module's docstring.
_GEN_COMMENT = "# generated by scripts/catbench_jobgen.py -- rerun this file to reproduce the run"


def render_model_script(spec: dict, mlip_name: str, benchmark: str, calc_num: int, d3: bool) -> str:
    """Render the per-model catbench script from a `resolve()` spec.

    Verbatim `resolve()` output: imports/inference lines are copied as-is,
    including any absolute host weight path they carry (F13). Byte-identical
    for the same inputs (AC7's determinism property, C3).
    """
    indent = "    "
    import_lines = "\n".join(spec["imports"])
    inference_lines = "\n".join(indent + ln for ln in spec["inference"])
    d3_import = "from catbench.dispersion import DispersionCorrection\n" if d3 else ""
    d3_apply = f"{indent}calc = DispersionCorrection().apply(calc)\n" if d3 else ""
    return _CATBENCH_TEMPLATE.format(
        d3_import=d3_import,
        import_lines=import_lines,
        calc_num=calc_num,
        inference_lines=inference_lines,
        d3_apply=d3_apply,
        mlip_name=mlip_name,
        benchmark=benchmark,
    )


def _render_body(spec: dict, jobfile: Path, workdir: Path) -> str:
    """The shared body of `render_runner_sh` and `render_slurm_sh`.

    Deliberately the ONLY place either renderer writes `cd`/`export`/`exec` —
    `render_slurm_sh`'s output always ENDS with exactly this text (see the
    byte-identical-below-the-header assertion in tests/test_catbench_jobgen.py),
    so local and SLURM cannot silently diverge.
    """
    lines = [
        _GEN_COMMENT,
        "set -eu",
        f'cd "{Path(workdir).resolve()}"',  # N4: catbench writes into cwd/result/
    ]
    for key, value in spec.get("env_run", {}).items():
        lines.append(f'export {key}="{value}"')
    lines.append(f'exec "{spec["python"]}" "{Path(jobfile).resolve()}"')
    return "\n".join(lines) + "\n"


def render_runner_sh(spec: dict, jobfile: Path, workdir: Path) -> str:
    """The AC7 unit: `set -eu`, `cd` to the absolute workdir, one `export`
    per `env_run` key, then `exec` the materialized `.py` (never `python -c`).
    """
    return "#!/bin/sh\n" + _render_body(spec, jobfile, workdir)


def render_slurm_sh(
    spec: dict,
    jobfile: Path,
    workdir: Path,
    *,
    job_name: str,
    partition: str = "gpu",
) -> str:
    """An SBATCH header followed by the IDENTICAL body as `render_runner_sh`.

    One body, two wrappers (C2/C17): local and SLURM execution stay a single
    source of truth. No `sbatch` is issued here or anywhere in this module —
    emission only.
    """
    workdir_abs = Path(workdir).resolve()
    header = "\n".join(
        [
            f"#SBATCH --job-name={job_name}",
            f"#SBATCH --partition={partition}",
            f"#SBATCH --output={workdir_abs}/jobs/{job_name}.slurm.out",
            f"#SBATCH --error={workdir_abs}/jobs/{job_name}.slurm.err",
            "#SBATCH --ntasks=1",
            "#SBATCH --gres=gpu:1",
        ]
    ) + "\n"
    return "#!/bin/sh\n" + header + _render_body(spec, jobfile, workdir)


def emit(
    spec: dict,
    mlip_name: str,
    benchmark: str,
    calc_num: int,
    d3: bool,
    workdir: Path,
    *,
    slurm: bool = False,
    partition: str = "gpu",
) -> dict:
    """Materialize `jobs/catbench_<mlip_name>.py` + `jobs/run_catbench_<mlip_name>.sh`
    (and, if `slurm`, `jobs/run_slurm_<mlip_name>.sh`) under `workdir`.

    Returns ``{"py": Path, "sh": Path[, "slurm": Path]}``. Writing twice with
    the same inputs produces byte-identical files (AC7's determinism
    property) — this function does not read the clock, the host, or any
    per-run state.
    """
    workdir = Path(workdir).resolve()
    jobs_dir = workdir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    py_path = jobs_dir / f"catbench_{mlip_name}.py"
    sh_path = jobs_dir / f"run_catbench_{mlip_name}.sh"
    py_path.write_text(render_model_script(spec, mlip_name, benchmark, calc_num, d3))
    sh_path.write_text(render_runner_sh(spec, py_path, workdir))
    sh_path.chmod(0o755)

    result = {"py": py_path, "sh": sh_path}
    if slurm:
        slurm_path = jobs_dir / f"run_slurm_{mlip_name}.sh"
        slurm_path.write_text(
            render_slurm_sh(
                spec, py_path, workdir,
                job_name=f"catbench_{mlip_name}", partition=partition,
            )
        )
        slurm_path.chmod(0o755)
        result["slurm"] = slurm_path
    return result


def _default_submit_hook(target: Path) -> int:
    """`sbatch <target>` for a SLURM script, `sh <target>` for a local runner."""
    target = Path(target)
    cmd = ["sbatch", str(target)] if target.name.startswith("run_slurm_") else ["sh", str(target)]
    return subprocess.run(cmd).returncode


def submit(target: Path, *, hook=None) -> int:
    """Dispatch one emitted `.sh` (never called under `--emit-only`).

    `hook` is injectable so callers (and tests) can verify dispatch without
    invoking a real scheduler or subprocess — the single hook C17/AC7's
    `--submit` flag is described as sitting behind.
    """
    fn = hook or _default_submit_hook
    return fn(Path(target))
