#!/usr/bin/env python3
"""ft_run.py <model> --dataset <path> [--out DIR] [--epochs N] [--emit-only]
[--slurm [--partition P]] -- resolve one variant's `finetune` block
(models.json, ingested from scripts/upstream_finetune.py in P2a) into a
concrete, materialized fine-tuning run.

Write-then-execute, same discipline as scripts/catbench_jobgen.py (P1): ALL
artifacts land on disk before anything runs --

  <out>/data/...                converted dataset (via scripts/ft_dataset.py)
  <out>/input.yaml|input.json   the patched training config, when the
                                 family's `selector_kind` is `config_key`
                                 (C6 -- a YAML/JSON-PATCHING path, not a flag
                                 builder: MACE and the deepmd family are the
                                 only `cli_flag` families)
  <out>/finetune_<version>.sh   the AC7 rerun unit: `set -eu`, `cd` to the
                                 absolute `<out>` dir (N4), one `export` per
                                 `env_run` key, then `exec` the real command
  <out>/slurm_finetune_<v>.sh   (--slurm) the IDENTICAL body under an SBATCH
                                 header (C17) -- emission only, never sbatch'd

Refusal gate, checked BEFORE any file is written:
  status in {not-supported, code-excavation-needed}  -> exit 2 (reason + any
                                                          evidence URLs)
  runnable_as_installed: false (after a live blocker  -> exit 3 (remaining
    recheck -- see `live_recheck_blockers`)              blockers, each
                                                          already phrased as
                                                          its own fix)

`live_recheck_blockers` re-verifies two blocker SHAPES against the actual
installed state rather than trusting the models.json snapshot forever: a
"pip install X" blocker is dropped once `import X` succeeds in the target
env's interpreter (so `pip install dpdata` between two ft_run.py invocations
is enough to unblock DeePMD/DPA4 without an ingestion re-run), and a
"symlink ... to a .pt name" blocker for the deepmd family is dropped
unconditionally because `build_deepmd` performs that exact symlink itself
before executing. Every other blocker shape is left standing -- ORB's
"finetune.py is not shipped in the wheel" blocker fetches a file and is
deliberately never auto-applied.

Only MACE, SevenNet and the deepmd family (DeePMD/DPA4) have a real,
upstream-doc-verbatim command builder (`BUILDERS`) -- these are the P3 demo
trio. Every other `documented`+`runnable_as_installed` family falls back to
`build_generic`, a best-effort renderer that assembles the registry
`entrypoint` + `selector_kind`/`selector_path` + `variant_args` generically;
it is exercised by `--emit-only` (never a real execution claim) and is
labelled as a stub in its own emitted config.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_SCRIPTS_DIR))

from oh_my_mlip import registry as reg  # noqa: E402

FT_DATASET = _SCRIPTS_DIR / "ft_dataset.py"

# Which ft_dataset.py --to alias each family's real command builder needs.
# Unlisted families default to "extxyz" in `build_generic` -- best-effort,
# since most of them are refused by the gate before a dataset is ever built.
FAMILY_DATASET_TARGET = {
    "MACE": "mace", "SevenNet": "sevennet", "NequIP": "nequip", "Allegro": "allegro",
    "GRACE": "grace", "MatterSim": "mattersim", "PET": "pet", "TACE": "tace",
    "DeePMD": "deepmd", "DPA4": "deepmd",
}

_GEN_COMMENT = "# generated by scripts/ft_run.py -- rerun this file to reproduce the fine-tune"

# Part 8 decision (a) / option B: advertise licence-gated fine-tunes, do not
# refuse them -- print the licence (+ a URL where the registry doesn't carry
# one itself) and proceed. oh-my-mlip is MIT and redistributes no weights
# either way; this is disclosure, not a capability gate.
_LICENCE_URLS = {
    "ASL": "https://github.com/ACEsuit/mace-foundations",
    "CC-BY-NC-SA-4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
}
_PIP_INSTALL_RE = re.compile(r"pip install ([A-Za-z0-9_\-.]+)")
_QUOTED_RE = re.compile(r"""['"]([^'"]+)['"]""")

# Family-specific overrides where the version's regular single-point
# `inference` line points at a DIFFERENT weight file than the one
# upstream_finetune.py's blockers name as the fine-tunable checkpoint (e.g.
# DeePMD's inference uses frozen-omat24.pth for single-point, but the
# FT-designated weight is dpa-3.1-3m-ft.pth, matching the version key
# DPA-3.1-3M-FT). Extracting from `inference` alone would silently fine-tune
# the wrong file.
_FOUNDATION_OVERRIDE = {
    "DPA-3.1-3M-FT": "${OH_MY_MLIP_HOME}/models/deepmd/dpa-3.1-3m-ft.pth",
}


@dataclass
class Context:
    family: str
    version: str
    finetune: dict
    resolved: dict
    out: Path
    epochs: int
    batch_size: int
    device: str
    dataset_paths: dict
    elements: list


@dataclass
class CommandSpec:
    argv: list
    config_path: Path | None = None
    config_text: str | None = None


# ── model/version/finetune resolution ────────────────────────────────────────
def load_finetune(model: str, version: str | None) -> tuple[str, str, dict, dict]:
    """Resolve `model` (family or version name) via the SAME name resolution
    as `oh_my_mlip.resolve()`, then read that version's `finetune` block
    straight out of models.json -- no separate/duplicated lookup logic."""
    resolved = reg.resolve(model, version)
    family, version = resolved["model"], resolved["version"]
    raw = reg.load_models()
    finetune = (raw[family]["versions"][version] or {}).get("finetune")
    if finetune is None:
        raise SystemExit(f"[ft_run] {family}/{version} has no 'finetune' block in models.json")
    return family, version, finetune, resolved


def entrypoint_bin(resolved: dict, name: str) -> str:
    """`<the resolved env's bin dir>/<name>` -- honors env adoption the same
    way `resolved['python']` already does (registry.resolve() rewrites
    'python' for an adopted env; every other console script in that env's
    bin/ moves with it)."""
    return str(Path(resolved["python"]).parent / name)


def _importable(python_bin: str, module: str) -> bool:
    if not Path(python_bin).exists():
        # Fresh clone: the env interpreter is not built yet, so no blocker fix
        # can be observed -- treat as not importable and let the caller's
        # refusal name the real remedy (install.sh) instead of tracing back.
        return False
    check = subprocess.run([python_bin, "-c", f"import {module}"], capture_output=True)
    return check.returncode == 0


def live_recheck_blockers(family: str, blockers: list[str], python_bin: str) -> list[str]:
    """Blockers whose fix has demonstrably already been applied are dropped;
    everything else is returned unchanged. See module docstring."""
    remaining = []
    for b in blockers:
        m = _PIP_INSTALL_RE.search(b)
        if m and _importable(python_bin, m.group(1)):
            continue
        if family in ("DeePMD", "DPA4") and "symlink" in b.lower():
            continue  # build_deepmd() performs this symlink itself
        remaining.append(b)
    return remaining


def resolve_foundation_checkpoint(version: str, resolved: dict) -> str:
    """The checkpoint/keyword this hub already trusts for `version` -- reused
    from `resolved['inference']` (the same weight validated for single-point)
    unless `_FOUNDATION_OVERRIDE` names a different FT-specific file."""
    override = _FOUNDATION_OVERRIDE.get(version)
    if override:
        return override.replace("${OH_MY_MLIP_HOME}", reg.home())
    for line in resolved["inference"]:
        m = _QUOTED_RE.search(line)
        if m:
            return m.group(1)
    raise SystemExit(f"[ft_run] could not extract a foundation checkpoint from {version}'s inference line")


def set_dotted(d: dict, dotted: str, value) -> None:
    parts = dotted.split(".")
    node = d
    for p in parts[:-1]:
        node = node.setdefault(p, {})
    node[parts[-1]] = value


# ── dataset conversion ────────────────────────────────────────────────────────
def run_ft_dataset(dataset: Path, target: str, out: Path, split: float, seed: int,
                   python_bin: str | None = None) -> dict:
    # The model env is the one interpreter guaranteed to carry ase/numpy; the
    # ambient interpreter that launched ft_run.py carries no such guarantee.
    cmd = [
        python_bin or sys.executable, str(FT_DATASET),
        "--input", str(dataset),
        "--split", str(split), "--seed", str(seed),
        "--to", target, "--out", str(out),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"[ft_run] ft_dataset.py failed (exit {proc.returncode})")
    return json.loads(proc.stdout.strip().splitlines()[-1])


# ── per-family command builders (the P3 demo trio) ───────────────────────────
def build_mace(ctx: Context) -> CommandSpec:
    foundation = resolve_foundation_checkpoint(ctx.version, ctx.resolved)
    variant_args = ctx.finetune.get("variant_args") or {}
    train_path, valid_path = ctx.dataset_paths["train"], ctx.dataset_paths.get("valid")
    argv = [
        entrypoint_bin(ctx.resolved, "mace_run_train"),
        f"--name={ctx.version}",
        f"--foundation_model={foundation}",
        "--multiheads_finetuning=False",  # C7/note: bare invocation defaults True in 0.3.15
        f"--train_file={train_path}",
        *( [f"--valid_file={valid_path}"] if valid_path else ["--valid_fraction=0.1"] ),
        "--energy_key=REF_energy",
        "--forces_key=REF_forces",
        "--E0s=average",
        "--lr=0.01",
        f"--batch_size={ctx.batch_size}",
        f"--max_num_epochs={ctx.epochs}",
        "--ema",
        "--ema_decay=0.99",
        "--default_dtype=float64",
        f"--device={ctx.device}",
        f"--model_dir={ctx.out}",
        f"--checkpoints_dir={ctx.out}/checkpoints",
        f"--log_dir={ctx.out}/logs",
        f"--results_dir={ctx.out}/results",
    ]
    for k, v in variant_args.items():
        argv.append(f"{k}={v}")
    return CommandSpec(argv=argv)


_SEVENNET_PRESET = {
    # SevenNet-Omni ships no dedicated preset file (only mf_ompa_fine_tune.yaml
    # and the generic fine_tune.yaml exist in installed sevenn 0.12.2.dev0) --
    # it falls back to the generic preset, a documented best-effort.
    "SevenNet-MF-OMPA": "mf_ompa_fine_tune",
}
# SevenNet-MF-ompa is a MULTI-MODAL checkpoint: its preset's data section
# expects `load_trainset_path`/`load_<modality>_validset_path` as
# `[{data_modality: ..., file_list: [{file: ...}]}]`, NOT a plain path list —
# a plain list raises `TypeError: ... is not dict or str` deep in
# sevenn.train.modal_dataset (host-verified, 2026-08-23). Versions absent
# here use the plain non-modal preset and need no modality name.
_SEVENNET_MODALITY = {"SevenNet-MF-OMPA": "mpa"}


def _sevenn_modal_path(modality: str, path: str) -> list:
    return [{"data_modality": modality, "file_list": [{"file": path}]}]


def build_sevennet(ctx: Context) -> CommandSpec:
    preset = _SEVENNET_PRESET.get(ctx.version, "fine_tune")
    preset_bin = entrypoint_bin(ctx.resolved, "sevenn_preset")
    proc = subprocess.run([preset_bin, preset], capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"[ft_run] sevenn_preset {preset} failed: {proc.stderr}")
    cfg = yaml.safe_load(proc.stdout)

    foundation = resolve_foundation_checkpoint(ctx.version, ctx.resolved)
    set_dotted(cfg, "train.continue.checkpoint", foundation)
    set_dotted(cfg, "train.continue.reset_optimizer", True)
    set_dotted(cfg, "train.continue.reset_scheduler", True)
    set_dotted(cfg, "train.continue.reset_epoch", True)
    set_dotted(cfg, "train.epoch", ctx.epochs)
    # mf_ompa_fine_tune.yaml sets no `per_epoch` at all (unlike the generic
    # fine_tune.yaml's per_epoch: 10) -- on a short demo run (epochs=2) that
    # leaves only the epoch-0 pre-training snapshot on disk. Force a
    # checkpoint every epoch so a `--epochs N` run always produces one.
    set_dotted(cfg, "train.per_epoch", 1)

    modality = _SEVENNET_MODALITY.get(ctx.version)
    valid = ctx.dataset_paths.get("valid")
    if modality:
        set_dotted(cfg, "data.load_trainset_path", _sevenn_modal_path(modality, str(ctx.dataset_paths["train"])))
        if valid:
            set_dotted(cfg, f"data.load_{modality}_validset_path", _sevenn_modal_path(modality, str(valid)))
    else:
        set_dotted(cfg, "data.load_trainset_path", [str(ctx.dataset_paths["train"])])
        if valid:
            set_dotted(cfg, "data.load_validset_path", [str(valid)])
    set_dotted(cfg, "data.batch_size", ctx.batch_size)
    for k, v in (ctx.finetune.get("variant_args") or {}).items():
        set_dotted(cfg, k, v)

    config_path = ctx.out / "input.yaml"
    config_text = yaml.safe_dump(cfg, sort_keys=False)
    argv = [entrypoint_bin(ctx.resolved, "sevenn"), "train", str(config_path)]
    return CommandSpec(argv=argv, config_path=config_path, config_text=config_text)


def build_deepmd(ctx: Context) -> CommandSpec:
    foundation = resolve_foundation_checkpoint(ctx.version, ctx.resolved)
    foundation_path = Path(os.path.expandvars(foundation))
    ckpt_for_cli = foundation_path
    if foundation_path.suffix == ".pth":
        # `dp --pt` dispatches on suffix -- symlink to a .pt name (the
        # blocker `live_recheck_blockers` drops unconditionally for this
        # exact reason).
        link = ctx.out / (foundation_path.stem + ".pt")
        if not (link.is_symlink() or link.exists()):
            link.symlink_to(foundation_path)
        ckpt_for_cli = link

    train_systems = ctx.dataset_paths.get("train_systems") or []
    valid_systems = ctx.dataset_paths.get("valid_systems") or []
    training: dict = {
        "training_data": {"systems": train_systems, "batch_size": "auto"},
        "numb_steps": max(int(ctx.epochs) * 100, 100),
        "disp_freq": 10,
        "save_freq": 50,
    }
    if valid_systems:
        training["validation_data"] = {"systems": valid_systems, "batch_size": "auto"}
    input_json = {
        # descriptor/fitting_net left empty: --use-pretrain-script (below)
        # pulls the real model section from the checkpoint (same reason
        # DPA4's upstream cmd uses it -- the local architecture is not
        # otherwise known to a hand-written input.json).
        "model": {"type_map": ctx.elements, "descriptor": {}, "fitting_net": {}},
        "learning_rate": {"type": "exp", "decay_steps": 100, "start_lr": 0.001, "stop_lr": 3.5e-5},
        "loss": {"type": "ener", "start_pref_e": 0.2, "limit_pref_e": 20, "start_pref_f": 100, "limit_pref_f": 60},
        "training": training,
    }
    config_path = ctx.out / "input.json"
    config_text = json.dumps(input_json, indent=2) + "\n"

    argv = [
        entrypoint_bin(ctx.resolved, "dp"), "--pt", "train", str(config_path),
        "--finetune", str(ckpt_for_cli), "--use-pretrain-script",
    ]
    return CommandSpec(argv=argv, config_path=config_path, config_text=config_text)


def build_generic(ctx: Context) -> CommandSpec:
    """Best-effort renderer for every family without a hand-verified builder
    above. Assembles `entrypoint` + `selector_kind`/`selector_path` +
    `variant_args` generically; the emitted config is explicitly labelled a
    stub. This is exercised by --emit-only only -- it is never claimed as a
    working command for a family whose gate lets it through."""
    finetune = ctx.finetune
    tokens = (finetune.get("entrypoint") or "").split()
    if not tokens:
        raise SystemExit(f"[ft_run] {ctx.family}/{ctx.version} declares no entrypoint to render")
    bin_path = entrypoint_bin(ctx.resolved, tokens[0])

    try:
        foundation = resolve_foundation_checkpoint(ctx.version, ctx.resolved)
    except SystemExit as exc:
        foundation = "<foundation-checkpoint-unresolved>"
        print(
            f"[ft_run] WARNING: {ctx.family}/{ctx.version}: could not resolve a "
            f"foundation checkpoint ({exc}) -- substituting "
            f"{foundation!r} into the emitted stub config instead of refusing "
            f"outright.",
            file=sys.stderr,
        )

    rest = []
    for tok in tokens[1:]:
        if tok.startswith("<") and tok.endswith(">"):
            rest.append(str(ctx.out / "finetune_config"))
        elif tok in ("input.yaml", "input.json") or tok.endswith((".yaml", ".yml")):
            rest.append(str(ctx.out / "finetune_config"))
        else:
            rest.append(tok)
    argv = [bin_path] + rest

    variant_args = finetune.get("variant_args") or {}
    config_path = None
    config_text = None
    selector_path = finetune.get("selector_path")
    if finetune.get("selector_kind") == "cli_flag" and selector_path and not selector_path.startswith("<"):
        argv.append(f"{selector_path}={foundation}")
        for k, v in variant_args.items():
            argv.append(f"{k}={v}")
    else:
        cfg = {
            "_generic_stub": (
                "best-effort ft_run.py rendering -- this family's real config "
                "schema is not modeled; see docs/finetune.md / AGENTS.md §3C"
            ),
            (selector_path or "checkpoint"): foundation,
        }
        cfg.update(variant_args)
        config_path = ctx.out / "finetune_config.json"
        config_text = json.dumps(cfg, indent=2) + "\n"
        # variant_args also appear on the command line (several families —
        # UMA included — pass them to an auxiliary CLI step, not the config).
        for k, v in variant_args.items():
            argv.append(f"{k}={v}")

    return CommandSpec(argv=argv, config_path=config_path, config_text=config_text)


BUILDERS = {
    "MACE": build_mace,
    "SevenNet": build_sevennet,
    "DeePMD": build_deepmd,
    "DPA4": build_deepmd,
}


# ── .sh rendering (same body-then-header pattern as catbench_jobgen.py) ─────
def _render_body(resolved: dict, argv: list[str], out_dir: Path) -> str:
    lines = [_GEN_COMMENT, "set -eu", f'cd "{Path(out_dir).resolve()}"']
    for key, value in (resolved.get("env_run") or {}).items():
        lines.append(f'export {key}="{value}"')
    lines.append("exec " + " ".join(shlex.quote(str(a)) for a in argv))
    return "\n".join(lines) + "\n"


def render_sh(resolved: dict, argv: list[str], out_dir: Path) -> str:
    return "#!/bin/sh\n" + _render_body(resolved, argv, out_dir)


def render_slurm(resolved: dict, argv: list[str], out_dir: Path, *, job_name: str, partition: str = "gpu") -> str:
    out_dir = Path(out_dir).resolve()
    header = "\n".join([
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --partition={partition}",
        f"#SBATCH --output={out_dir}/{job_name}.slurm.out",
        f"#SBATCH --error={out_dir}/{job_name}.slurm.err",
        "#SBATCH --ntasks=1",
        "#SBATCH --gres=gpu:1",
    ]) + "\n"
    return "#!/bin/sh\n" + header + _render_body(resolved, argv, out_dir)


# ── CLI ───────────────────────────────────────────────────────────────────────
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("model", help="framework or version name from models.json")
    ap.add_argument("--version", default=None, help="specific version (default: family default_version)")
    ap.add_argument("--dataset", required=True, type=Path, help="anything ase.io.read handles")
    ap.add_argument("--out", default=None, help="output directory (default: ft_<family>)")
    ap.add_argument("--epochs", type=int, default=2)
    ap.add_argument("--batch-size", type=int, default=2)
    ap.add_argument("--device", default="cuda", choices=["cuda", "cpu"])
    ap.add_argument("--split", type=float, default=0.9)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--emit-only", action="store_true", help="write artifacts, never execute")
    ap.add_argument("--slurm", action="store_true", help="also emit an SBATCH-wrapped script (never sbatch'd)")
    ap.add_argument("--partition", default="gpu")
    args = ap.parse_args()

    try:
        family, version, finetune, resolved = load_finetune(args.model, args.version)
    except reg.RegistryError as exc:
        print(f"[ft_run] {exc}", file=sys.stderr)
        return 1

    status = finetune.get("status")
    if status in ("not-supported", "code-excavation-needed"):
        print(f"[ft_run] {family}/{version}: finetuning is {status} -- "
              f"{finetune.get('reason') or 'no reason recorded'}", file=sys.stderr)
        for url in finetune.get("evidence") or []:
            print(f"  evidence: {url}", file=sys.stderr)
        return 2

    blockers = list(finetune.get("blockers") or [])
    remaining = live_recheck_blockers(family, blockers, resolved["python"])
    if not finetune.get("runnable_as_installed"):
        if remaining:
            print(f"[ft_run] {family}/{version}: not runnable as installed:", file=sys.stderr)
            for b in remaining:
                print(f"  blocker: {b}", file=sys.stderr)
            if not Path(resolved["python"]).exists():
                print(f"  (the env interpreter {resolved['python']} does not exist -- "
                      f"build it first: ./install.sh {resolved['env']})", file=sys.stderr)
            return 3
        if not blockers:
            # runnable_as_installed:false with an empty blocker list: nothing
            # to live-recheck, so the registry flag stands (schema forbids
            # this shape, but a hand-edited registry must not slip through).
            print(f"[ft_run] {family}/{version}: registry marks this variant not "
                  f"runnable as installed and lists no verifiable blockers -- refusing.",
                  file=sys.stderr)
            return 3
        # every declared blocker demonstrably cleared -> proceed.

    licence = finetune.get("licence")
    if licence:
        url = resolved.get("license_url") or _LICENCE_URLS.get(licence, "")
        note = f"[ft_run] NOTE: {version}'s checkpoint carries a non-permissive licence: {licence}"
        if url:
            note += f" ({url})"
        print(note + " -- oh-my-mlip is MIT and redistributes no weights; "
              "a fine-tuned derivative inherits this licence's terms.", file=sys.stderr)

    out = Path(args.out).resolve() if args.out else (Path.cwd() / f"ft_{family}").resolve()
    out.mkdir(parents=True, exist_ok=True)

    target = FAMILY_DATASET_TARGET.get(family, "extxyz")
    conv = run_ft_dataset(args.dataset, target, out / "data", args.split, args.seed,
                          python_bin=resolved["python"])

    ctx = Context(
        family=family, version=version, finetune=finetune, resolved=resolved, out=out,
        epochs=args.epochs, batch_size=args.batch_size, device=args.device,
        dataset_paths=conv["outputs"], elements=conv["elements"],
    )
    builder = BUILDERS.get(family, build_generic)
    spec = builder(ctx)

    if spec.config_path is not None:
        spec.config_path.write_text(spec.config_text)

    sh_path = out / f"finetune_{version}.sh"
    sh_path.write_text(render_sh(resolved, spec.argv, out))
    sh_path.chmod(0o755)
    print(f"[ft_run] wrote {sh_path}")

    if args.slurm:
        slurm_path = out / f"slurm_finetune_{version}.sh"
        slurm_path.write_text(render_slurm(resolved, spec.argv, out, job_name=f"finetune_{version}", partition=args.partition))
        slurm_path.chmod(0o755)
        print(f"[ft_run] wrote {slurm_path} (emit-only -- sbatch it yourself)")
        return 0

    if args.emit_only:
        return 0

    print(f"[ft_run] executing {sh_path}")
    return subprocess.run(["bash", str(sh_path)]).returncode


if __name__ == "__main__":
    raise SystemExit(main())
