#!/usr/bin/env python3
"""Generate an exact-replay lock for one env from a passing fresh-root campaign.

Inputs are the inventory files a setup_sweep --fresh-root cycle preserves:
  <inventory>/<env>.conda_explicit.txt   (conda list --explicit)
  <inventory>/<env>.pip_freeze.txt       (pip freeze)
Outputs (consumed by `OMM_USE_LOCK=1 ./install.sh <env>`):
  envs/locks/<env>.conda.txt   the @EXPLICIT package URL list, verbatim
  envs/locks/<env>.pip.txt     index/find-links lines + every pip pin, installed
                               with `pip install --no-deps -r` (no resolution)

pip freeze lists conda-installed Python packages as
`name @ file:///home/conda/feedstock_root/...` (conda-forge build paths that do
not exist on any user machine); conda supplies those, so they are dropped. Any
other local path, editable install or unpinned line is refused: the lock would
not be reproducible.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CONDA_BUILD_PREFIX = "file:///home/conda/feedstock_root/"
INDEX_FLAGS = ("--extra-index-url", "--index-url", "--find-links", "-f")


def index_lines(env: str, envs_dir: Path) -> list[str]:
    """Index / find-links options the recipe (yml pip block or build sidecar) used."""
    found: list[str] = []
    recipe = envs_dir / f"{env}.yml"
    if recipe.is_file():
        for raw in recipe.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line.startswith("- "):
                line = line[2:].strip()
            if line.split(" ", 1)[0] in INDEX_FLAGS:
                found.append(line)
    sidecar = envs_dir / f"{env}.build.sh"
    if sidecar.is_file():
        text = sidecar.read_text(encoding="utf-8")
        for flag, url in re.findall(r"(--extra-index-url|--index-url|--find-links|-f)\s+(https?://\S+)", text):
            found.append(f"{flag} {url}")
    out: list[str] = []
    for line in found:
        line = "--find-links " + line[3:] if line.startswith("-f ") else line
        if line not in out:
            out.append(line)
    return out


def pip_pins(freeze: Path) -> tuple[list[str], list[str]]:
    pins: list[str] = []
    refused: list[str] = []
    for raw in freeze.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if f" @ {CONDA_BUILD_PREFIX}" in line:
            continue
        if line.startswith("-e ") or " @ file://" in line:
            refused.append(line)
        elif "==" in line or " @ " in line:
            pins.append(line)
        else:
            refused.append(line)
    return pins, refused


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--env", required=True)
    ap.add_argument("--inventory", required=True, type=Path, help="campaign <root>/.sweep/inventory directory")
    ap.add_argument("--out-dir", type=Path, default=REPO / "envs" / "locks")
    ap.add_argument("--source", default=None, help="provenance label written into the headers")
    args = ap.parse_args(argv)

    explicit = args.inventory / f"{args.env}.conda_explicit.txt"
    freeze = args.inventory / f"{args.env}.pip_freeze.txt"
    for p in (explicit, freeze):
        if not p.is_file():
            print(f"gen_env_lock: missing {p}", file=sys.stderr)
            return 2
    conda_text = explicit.read_text(encoding="utf-8")
    if "@EXPLICIT" not in conda_text:
        print(f"gen_env_lock: {explicit} is not a conda --explicit list", file=sys.stderr)
        return 2
    pins, refused = pip_pins(freeze)
    if refused:
        print(f"gen_env_lock: {args.env}: not reproducible, refusing:", file=sys.stderr)
        for line in refused:
            print(f"  {line}", file=sys.stderr)
        return 3

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source = args.source or str(args.inventory)
    header = [
        f"# oh-my-mlip exact-replay lock for env '{args.env}' (generated by scripts/gen_env_lock.py)",
        f"# source: {source}",
        f"# generated: {stamp}",
        f"# replay: OMM_USE_LOCK=1 ./install.sh {args.env}",
    ]
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / f"{args.env}.conda.txt").write_text("\n".join(header) + "\n" + conda_text, encoding="utf-8")
    pip_lines = header + ["# installed with: pip install --no-deps -r <this file>"] + index_lines(args.env, REPO / "envs") + pins
    (args.out_dir / f"{args.env}.pip.txt").write_text("\n".join(pip_lines) + "\n", encoding="utf-8")
    n_conda = sum(1 for line in conda_text.splitlines() if line.startswith("http"))
    print(f"{args.env}: conda {n_conda} packages, pip {len(pins)} pins -> {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
